"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "mn" | "en";

export const translations = {
  mn: {
    // Navigation & common
    settings: "Тохиргоо",
    logout: "Гарах",
    back: "Буцах",
    save: "Хадгалах",
    cancel: "Болих",
    loading: "Ачааллаж байна...",
    error: "Алдаа",
    success: "Амжилттай",
    delete: "Устгах",
    edit: "Засах",
    search: "Хайх",
    close: "Хаах",
    confirm: "Баталгаажуулах",

    // Settings page
    settingsTitle: "Тохиргоо",
    settingsSubtitle: "Профайл болон аюулгүй байдлын тохиргоо",
    profileImage: "Профайл зураг",
    profileImageDesc: "Өөрийн профайл зургаа солих",
    changeImage: "Зураг сонгох",
    removeImage: "Зураг устгах",
    imageSuccess: "Профайл зураг амжилттай солигдлоо",
    imageRemoved: "Профайл зураг устгагдлаа",
    imageError: "Зураг хадгалахад алдаа гарлаа",
    imageTooBig: "Зураг хэт том байна. Жижиг зураг сонгоно уу.",
    imageHint1: "Хамгийн ихдээ 5MB хэмжээтэй зураг",
    imageHint2: "Автоматаар 300x300 хэмжээтэй болгоно",
    imageHint3: "JPG, PNG, GIF форматтай байх",

    changePassword: "Нууц үг солих",
    changePasswordDesc: "Аюулгүй байдлын тулд шинэ нууц үг үүсгэх",
    currentPassword: "Одоогийн нууц үг",
    newPassword: "Шинэ нууц үг",
    confirmPassword: "Нууц үг баталгаажуулах",
    currentPasswordPlaceholder: "Одоогийн нууц үгээ оруулна уу",
    newPasswordPlaceholder: "Шинэ нууц үгээ оруулна уу",
    confirmPasswordPlaceholder: "Нууц үгээ дахин оруулна уу",
    passwordRequirements: "Нууц үгийн шаардлага:",
    passwordReq1: "Хамгийн багадаа 8 тэмдэгт",
    passwordReq2: "Том үсэг агуулсан (A-Z)",
    passwordReq3: "Жижиг үсэг агуулсан (a-z)",
    passwordReq4: "Тоо агуулсан (0-9)",
    passwordReq5: "Тусгай тэмдэгт агуулсан (@$!%*?&#)",
    passwordChanging: "Солиж байна...",
    passwordChanged: "Нууц үг амжилттай солигдлоо",
    passwordMismatch: "Шинэ нууц үг таарахгүй байна",
    passwordInvalid: "Нууц үг шаардлагыг хангахгүй байна",
    passwordFillAll: "Бүх талбарыг бөглөнө үү",
    passwordChangeBtn: "Нууц үг солих",

    language: "Хэл",
    languageDesc: "Системийн харуулах хэлийг сонгоно уу",
    mongolian: "Монгол",
    english: "English",

    // Navigation
    navHome: "Нүүр",
    navDepartments: "Хэлтэс",
    navNews: "Мэдээ",
    navTools: "Хэрэгслүүд",
    navAdmin: "Админ",
    navAdminPanel: "Админ самбар",
    navUsers: "Хэрэглэгч",
    navTheme: "Загвар",
    navProfileSettings: "Профайл тохиргоо",

    // Common UI
    dashboard: "Хяналтын самбар",
    tools: "Хэрэгслүүд",
    admin: "Админ",
    notifications: "Мэдэгдэл",
    profile: "Профайл",
    department: "Хэлтэс",

    // Hero greetings
    greetingMorning: "Өглөөний мэнд",
    greetingAfternoon: "Өдрийн мэнд",
    greetingEvening: "Оройн мэнд",
    defaultEmployee: "Ажилтан",
    defaultUser: "Хэрэглэгч",
    defaultDepartment: "Дотоод Аудитын Газар",
    defaultPosition: "Дата инженер",
    loadingText: "Ачаалж байна...",
    toolsButton: "Хэрэгслүүд",

    // Auth
    needLogin: "Нэвтрэх шаардлагатай",
    needLoginToolsDesc: "Хэрэгслүүдийг ашиглахын тулд нэвтэрнэ үү.",
    needLoginDeptDesc: "Энэ хуудсыг үзэхийн тулд нэвтэрнэ үү.",

    // Tools page
    toolsPageTitle: "Хэрэгсэл",
    toolsPageSubtitle: "Дотоод аудитын газар",
    toolsOpen: "Нээх",
    toolsFree: "Чөлөөт хэрэгслүүд",
    toolsWork: "Ажлын хэрэгслүүд",
    toolsNoneFound: "Хэрэгсэл олдсонгүй",
    toolsNoneDesc: "Танд ашиглах боломжтой хэрэгсэл байхгүй байна. Админтай холбогдож эрх авна уу.",
    toolTodoTitle: "Хийх зүйлсийн жагсаалт",
    toolTodoDesc: "Өдөр тутмын ажлуудаа үр дүнтэй төлөвлөж, хянах боломжтой хэрэгсэл",
    toolChessTitle: "Оюуны спорт",
    toolChessDesc: "Шатар тоглоом — хамт олныхоо гишүүнтэй онлайнаар тоглох боломж",
    toolSampleTitle: "Санамсаргүй түүвэр",
    toolSampleDesc: "Аудитын санамсаргүй түүвэр гаргах хэрэгсэл",
    toolPivotTitle: "Pivot",
    toolPivotDesc: "Excel файлаас pivot хүснэгт үүсгэх",
    toolReportTitle: "Улирлын тайлан",
    toolReportDesc: "Улирлын ажлын тайлан бэлтгэх",
    toolDbRequestTitle: "Эрх Хүсэх",
    toolDbRequestDesc: "ClickHouse хүснэгтэд хандах эрх хүсэх, өөрийн хүсэлтүүдийг хянах",
    toolDbGrantTitle: "Эрх Олгох",
    toolDbGrantDesc: "ClickHouse хандалтын хүсэлтүүдийг хянаж удирдах",
    toolEnglishTitle: "Англи үгс",
    toolEnglishDesc: "Англи үгийн санг бүрдүүлж, flash card болон тест горимоор цээжлэх",
    toolExcelTitle: "Excel тайлан",
    toolExcelDesc: "Системийн мэдээллээс динамик Python кодоор Excel тайлан үүсгэж татах",
    toolPdfTitle: "PDF → Текст",
    toolPdfDesc: "PDF файлыг текст болгон хөрвүүлж, хуулж авах боломжтой хэрэгсэл",
    toolDataDocTitle: "Өгөгдлийн толь бичиг",
    toolDataDocDesc: "ClickHouse мэдээллийн сангийн бүтэц, баганын тайлбар, код сан",
    toolAlertBoxTitle: "Alert Box",
    toolAlertBoxDesc: "Банкны гүйлгээний эрсдэлийн шинжилгээ, CIF хайлт, улаан тугийн мэдэгдэл",

    // Departments page
    albumTitle: "Альбом",
    addPhoto: "Зураг нэмэх",
    uploadPhotoPrompt: "Хамт олны зураг оруулах",
    photoSizeHint: "PNG, JPG, WEBP · дээд тал 3MB",
    photosSuffix: "зураг",
    photoSizeError: "Зургийн хэмжээ 3MB-аас бага байх шаардлагатай",
    photoAdded: "Зураг нэмэгдлээ",
    photoUploadError: "Зураг оруулахад алдаа гарлаа",
    deleteError: "Устгахад алдаа гарлаа",
    confirmDeletePhoto: "Энэ зурагийг устгах уу?",
    collapseText: "Хураах",
    showMoreText: "Цааш харах",
    activeStatus: "Идэвхтэй",
    inactiveStatus: "Идэвхгүй",
    managerBadge: "Дарга",
    youBadge: "Та",
    myDept: "Миний хэлтэс",
    employeeSuffix: "ажилтан",
    managerLabel: "Менежер",
    missionTitle: "Чиг үүрэг",
    missionSubtitle: "Хэлтсийн үндсэн зорилго",
    noDescription: "Тайлбар оруулаагүй байна. Админ энэ мэдээллийг нэмж болно.",
    teamTitle: "Хамт олон",
    teamSubtitle: "Хэлтсийн бүрэлдэхүүн",
    noEmployees: "Ажилтан бүртгэгдээгүй байна",
    otherDeptsTitle: "Бусад хэлтсүүд",
    otherDeptsSubtitle: "Байгууллагын бүтэц",
    noOtherDepts: "Бусад хэлтэс олдсонгүй.",
    deptUnknownTitle: "Хэлтэс тодорхойгүй",
    deptUnknownDesc: "Таны хэлтэс тодорхойлогдоогүй байна. Админтай холбогдоно уу.",
    deptsLoadError: "Хэлтсүүдийн жагсаалт ачаалахад алдаа гарлаа.",
    deptDetailLoadError: "Хэлтсийн дэлгэрэнгүй мэдээлэл ачаалахад алдаа гарлаа.",
    deptLoadError: "Хэлтсийн мэдээлэл ачаалахад алдаа гарлаа.",

    // News page
    newsTitle: "Мэдээ",
    newsSubtitle: "DaHews — Дотоод аудитын мэдээ",
    latestNews: "Сүүлийн мэдээнүүд",
    otherNews: "Бусад мэдээнүүд",
    noNews: "Мэдээ байхгүй байна",
    readMore: "Дэлгэрэнгүй",
    minRead: "мин",
    minuteRead: "минут унших",
    newsLoading: "Мэдээ ачаалж байна...",
    newsDefaultAuthor: "Дотоод аудитын алба",
    internalAuditLabel: "Дотоод аудит — DAHUB",
    internalAuditDept: "Дотоод аудитын газар",
    newsCreateTitle: "Мэдээ нэмэх",
    newsCreateBtn: "Нийтлэх",
    newsFormTitle: "Гарчиг",
    newsFormContent: "Агуулга",
    newsFormCategory: "Ангилал",
    newsFormImage: "Зураг",
    newsFormImageHint: "Зураг оруулах (2MB хүртэл)",
    newsCreateSuccess: "Мэдээ амжилттай нийтлэгдлээ!",
    newsCreateError: "Мэдээ нэмэхэд алдаа гарлаа",
    newsStatsTitle: "Шилдэг нийтлэгчид",
    newsStatsRank: "#",
    newsStatsAuthor: "Нийтлэгч",
    newsStatsCount: "Мэдээ",
    newsStatsViews: "Нийт үзэлт",
    newsStatsEmpty: "Одоогоор мэдээлэл байхгүй",
    newsDelete: "Устгах",
    newsDeleteConfirm: "Энэ мэдээг устгах уу?",
    newsDeleteError: "Мэдээ устгахад алдаа гарлаа",

    // Tailan (Quarterly Report) tool
    tailan_loading: "Уншиж байна…",
    tailan_title: "Улирлын тайлан",
    tailan_subtitle: "Улирлын ажлын тайлан бэлтгэх, нэгтгэх систем",
    tailan_myReport: "Өөрийн тайлан",
    tailan_privateTag: "Хувийн",
    tailan_myReportDesc: "Тайлангаа бэлтгэж хэлтсийн ахлагч руу илгээх",
    tailan_deptReport: "Хэлтсийн тайлан",
    tailan_headTag: "Ахлагч",
    tailan_deptReportDesc: "Гишүүдийн тайлануудыг нэгтгэж нэк баримт болгох",
    tailan_membersView: "Гишүүдийн тайлан харах",
    tailan_viewTag: "Харах",
    tailan_membersViewDesc: "Хэлтсийн гишүүдийн илгээсэн тайлануудыг харах",
    tailan_myReportTitle: "Миний тайлан",
    tailan_downloadWord: "Word татах",
    tailan_submitReport: "Илгээх",
    tailan_cyrillicName: "Нэр (кириллээр)",
    tailan_cyrillicNamePlaceholder: "Тайланд бичигдэх нэрээ оруулна уу",
    tailan_yearLabel: "Он",
    tailan_quarterLabel: "Улирал",
    tailan_s1Title: "I. Дата анализын үр дүнгээр аудитын үйл ажиллагааг дэмжсэн байдал",
    tailan_s12Title: "I.2 Шинээр хөгжүүлсэн Дашбоард хөгжүүлэлтийн чанар, үр дүн",
    tailan_s2Title: "II. Аудитын үйл ажиллагаанд шаардлагатай өгөгдөл боловсруулах ажил",
    tailan_s3Title: "III. Тогтмол хийгддэг ажлууд",
    tailan_s31Title: "III.1 Өгөгдөл боловсруулалт автоматжуулалтыг цаг хугацаанд нь гүйцэтгэсэн байдал",
    tailan_s32Title: "III.2 Дашбоардын хэвийн ажиллагааг хангаж ажилласан байдал",
    tailan_s4Title: "IV. Хамрагдсан сургалт",
    tailan_s41Title: "IV.1 Сургалтаас олж авсан мэдлэгээ ашиглаж буй байдал",
    tailan_s5Title: "V. Үүрэг даалгаварын биелэлт",
    tailan_s6Title: "VI. Хамт олны ажил",
    tailan_s7Title: "VII. Шинэ санал санаачилга",
    tailan_dynTitle: "Нэмэлт хэсгүүд (VIII, IX, …)",
    tailan_showInReport: "Тайланд харуулах",
    tailan_hideFromReport: "Тайлангаас нуух",
    tailan_addTask: "Ажил нэмэх",
    tailan_addEntry: "Нэмэх",
    tailan_addTraining: "Сургалт нэмэх",
    tailan_addSection: "Нэмэлт хэсэг нэмэх",
    tailan_taskNameLabel: "Ажлын нэр",
    tailan_taskDescLabel: "Гүйцэтгэл /тайлбар/",
    tailan_detailedDescPlaceholder: "Дэлгэрэнгүй тайлбар бичнэ үү...",
    tailan_taskNamePlaceholder: "Ажлын нэр...",
    tailan_plannedTaskLabel: "Төлөвлөгөөт ажил",
    tailan_taskCompletionPct: "Ажлын гүйцэтгэл (%)",
    tailan_periodLabel: "Хийгдсэн хугацаа",
    tailan_startDateLabel: "Эхлэх огноо",
    tailan_endDateLabel: "Дуусах огноо",
    tailan_taskSummaryLabel: "Гүйцэтгэл /товч/",
    tailan_briefSummaryPlaceholder: "Товч тайлбар...",
    tailan_plannedTaskPlaceholder: "Төлөвлөгөөт ажлын нэр...",
    tailan_autoTaskPlaceholder: "Тогтмол хийгддэг автоматжуулалт...",
    tailan_valueUsagePlaceholder: "Ач холбогдол/хэрэглээ...",
    tailan_userRatingPlaceholder: "Хэрэглэгчийн үнэлгээ (0-100)",
    tailan_dashboardNamePlaceholder: "Dashboard нэр...",
    tailan_clientRatingPlaceholder: "Хэрэглэгч нэгжийн үнэлгээ (0-100)",
    tailan_trainingNamePlaceholder: "Сургалтын нэр...",
    tailan_organizerLabel: "Зохион байгуулагч",
    tailan_trainingTypeLabel: "Сургалтын төрөл",
    tailan_selectOption: "-- Сонгох --",
    tailan_externalTraining: "Гадаад",
    tailan_internalTraining: "Дотоод",
    tailan_trainingFormatLabel: "Сургалтын хэлбэр",
    tailan_onlineFormat: "Онлайн",
    tailan_inPersonFormat: "Танхим",
    tailan_hoursLabel: "Цаг",
    tailan_meetsGoalLabel: "Аудитын зорилгод нийцсэн эсэх",
    tailan_meetsGoalYes: "Нийцсэн",
    tailan_meetsGoalNo: "Нийцээгүй",
    tailan_sharedKnowledgeLabel: "Мэдлэгээ хуваалцсан эсэх",
    tailan_sharedKnowledgeYes: "Хуваалцсан",
    tailan_sharedKnowledgeNo: "Хуваалцаагүй",
    tailan_knowledgeUsagePlaceholder: "Сургалтаас авсан мэдлэгийг хэрхэн ашиглаж байгаа тухай...",
    tailan_taskTypePlaceholder: "Ажлын төрөл...",
    tailan_completedWorkPlaceholder: "Хийгдсэн ажил...",
    tailan_teamActivityPlaceholder: "Хамт олны ажил...",
    tailan_initiativeLabel: "Санаачилга",
    tailan_proposalPlaceholder: "Шинэ санал санаачилга, дэвшүүлсэн санааг бичнэ үү...",
    tailan_sectionTitlePlaceholder: "Хэсгийн гарчиг...",
    tailan_sectionContentPlaceholder: "Хэсгийн агуулга...",
    tailan_livePreview: "Realtime preview — Word баримт",
    tailan_dateLabel: "Огноо",
    tailan_viewReportTitle: "Тайлан харах",
    tailan_reportLoading: "Тайлан ачааллаж байна…",
    tailan_noReportSubmitted: "энэ улиралд тайлан илгээгээгүй байна.",
    tailan_noReportsThisQuarter: "Энэ улиралд бүртгэсэн тайлан байхгүй",
    tailan_submitted: "Илгээсэн",
    tailan_draft: "Ноорог",
    tailan_submittedAtLabel: "Илгээсэн:",
    tailan_updatedAtLabel: "Шинэчилсэн:",
    tailan_viewReportHint: "Тайлан харах",
    tailan_deptReportPageTitle: "Хэлтсийн улирлийн тайлан",
    tailan_savingLabel: "Хадгалаж байна...",
    tailan_collapseSidebar: "Хураах",
    tailan_expandSidebar: "Дэлгэх",
    tailan_evalTitle: "Нэгтгэл / Дүгнэлт",
    tailan_totalScoreLabel: "Нийт оноо:",
    tailan_allSectionsOverview: "Бүх төлөвийн нэгтгэл",
    tailan_s1Label: "ТУЗ болон аудитын хорооны төлөв",
    tailan_s2Label: "Харилцагчийн төлөв",
    tailan_s3Label: "Дотоод үйл ажиллагааны төлөв",
    tailan_s4Label: "Сургалт хөгжлийн төлөв",
    tailan_scorePointsSuffix: "оноо",
    tailan_detailedEvalTable: "Дэлгэрэнгүй үнэлгээний хүснэгт",
    tailan_groupCol: "Бүлэг",
    tailan_keyIndicatorCol: "Түлхүүр үзүүлэлт",
    tailan_weightCol: "Хувь",
    tailan_scoreCol: "Үнэлгээ",
    tailan_scoreDescCol: "Үнэлгээний тайлбар",
    tailan_subtotalRow: "Нийт",
    tailan_grandTotalRow: "НИЙТ",
    tailan_signatureSection: "Гарын үсэг",
    tailan_namePlaceholder: "Нэр...",
    tailan_titleJobPlaceholder: "/Албан тушаал/",
    tailan_preparedBy: "БОЛОВСРУУЛСАН:",
    tailan_evaluatedBy: "ҮНЭЛЖ, БАТАЛГААЖУУЛСАН:",
    tailan_previewSection: "Урьдчилан харах",
    tailan_lastSavedLabel: "Сүүлд:",
    tailan_s4DetailedLabel: "Сургалт, хөгжлийн төлөв байдалын дэлгэрэнгүй тайлбар:",
    tailan_s4DetailedPlaceholder: "Сургалт, хөгжлийн ажлын талаар дэлгэрэнгүйгээр бичнэ...",
    tailan_generalDescLabel: "Ерөнхий тайлбар",
    tailan_generalDescPlaceholder: "Энэ тэлэвийн хүрээнд хийсэн ажил, үйл ажиллагааны талаар дэлгэрэнгүй тайлбар бичнэ...",
    tailan_achievementsLabel: "Амжилт, давуу тал",
    tailan_achievementsPlaceholder: "Тайлант хугацаанд гарсан амжилт, сайн үр дүн, давуу талыг тэмдэглэнэ...",
    tailan_challengesLabel: "Бэрхшээл, сорилт",
    tailan_challengesPlaceholder: "Тайлант хугацаанд тулгарсан бэрхшээл, шийдвэрлэх шаардлагатай асуудлуудыг тэмдэглэнэ...",
    tailan_widthLabel: "Өргөн:",
    tailan_heightLabel: "Өндөр:",
    tailan_addImageBtn: "+ Зураг нэмэх",
    tailan_noDataRow: "— Мэдээлэл байхгүй —",
    tailan_productNamePlaceholder: "Бүтээгдэхүүний нэр...",
    tailan_sectionNamePlaceholder: "Хэсгийн нэр...",
    tailan_importFromMyReportBtn: "Хувийн тайланаас татах",
    tailan_descriptionTextLabel: "Тайлбар текст",
    tailan_descriptionTextPlaceholder: "Тайлант хугацаанд хэмнэсэн нөөц, цаг хугацааны талаарх тайлбар...",
    tailan_dataProductCol: "ДАТА БҮТЭЭГДЭХҮҮН",
    tailan_productTypeCol: "БҮТЭЭГДЭХҮҮНИЙ ТӨРӨЛ",
    tailan_savedDaysCol: "ХЭМНЭСЭН ХҮН/ӨДӨР",
    tailan_noTasksMsg: "Ажил байхгүй — \"Хувийн тайланаас татах\" эсвэл \"+\" товч дарна уу",
    tailan_clickToImportMsg: "Татах товч дарна уу",
    tailan_plannedTasksCol: "Төлөвлөгөөт ажил (Дууссан ажлууд)",
    tailan_completionCol: "Ажлын гүйцэтгэл",
    tailan_periodCol: "Хийгдсэн хугацаа",
    tailan_completionBriefCol: "Гүйцэтгэл /товч/",
    tailan_dataProcessingCol: "Өгөгдөл боловсруулалт",
    tailan_valueUsageCol: "Ач холбогдол хэрэглээ",
    tailan_clientRatingCol: "Хэрэглэгч үнэлгээ",
    tailan_avgRow: "Дундаж",
    tailan_addRowBtn: "+ Мөр нэмэх",
    tailan_addTaskBtn: "+ Ажил нэмэх",
    tailan_imageWidthSettings: "Зургуудын өргөн тохиргоо",
    tailan_unnamedTask: "(нэргүй)",
    tailan_periodPlaceholder: "Хугацаа...",
    tailan_completionBriefPlaceholder: "Гүйцэтгэл /товч/...",
    tailan_valueUsagePlaceholder2: "Ач холбогдол, хэрэглээ...",
    tailan_ratingPlaceholder: "Үнэлгээ...",
    tailan_group14New: "Тайлант хугацаанд шинээр нэвтрүүлсэн дата бүтээгдэхүүн",
    tailan_group14Used: "Тайлант хугацаанд аудитын үйл ажиллагаанд ашигласан дата бүтээгдэхүүн",
    tailan_recurringDataCol: "Тогтмол хийгддэг өгөгдөл боловсруулалт",
    tailan_dashboardValueCol: "Dashboard-ийн ач холбогдол хэрэглээ",
    tailan_noItemsMsg: "Зүйл байхгүй — \"+ Зүйл нэмэх\" товч дарна уу",
    tailan_itemTitlePlaceholder: "Гарчиг...",
    tailan_bulletTextPlaceholder: "Буллет текст...",
    tailan_addBulletBtn: "+ Буллет нэмэх",
    tailan_addItemBtn: "+ Зүйл нэмэх",
    tailan_employeeNamePlaceholder: "Ажилтаны нэр...",
    tailan_knowledgeAppliedPlaceholder: "Мэдлэг ашиглалтын тайлбар... (шинэ мөрөөнд буллет байдлаар харагдана)",
    tailan_employeeCol: "Ажилтан",
    tailan_trainingNameCol: "Сургалтын нэр",
    tailan_organizerCol: "Зохион байгуулагч",
    tailan_typeCol: "Төрөл",
    tailan_dateCol: "Огноо",
    tailan_formatCol: "Хэлбэр",
    tailan_hoursCol: "Цаг",
    tailan_meetsAuditGoalCol: "Аудитын зорилготой холбогдсон",
    tailan_sharedKnowledgeCol: "Мэдлэг хуваалцсан",
    tailan_s43EmployeePlaceholder: "Ажилтан...",
    tailan_s43TrainingPlaceholder: "Сургалт...",
    tailan_s43OrganizerPlaceholder: "Зохион байгуулагч...",
    tailan_s43TypePlaceholder: "Төрөл...",
    tailan_s43DatePlaceholder: "Огноо...",
    tailan_s43FormatPlaceholder: "Хэлбэр...",
    tailan_s43HoursPlaceholder: "Цаг...",
    tailan_s43MeetsPlaceholder: "Тийм/Үгүй...",
    tailan_s43KnowledgePlaceholder: "Мэдлэг...",
    tailan_kpiIndicatorPlaceholder: "Үзүүлэлт...",
    tailan_kpiEvaluationPlaceholder: "Тайлбар...",
    tailan_scoreExcellent: "Маш сайн",
    tailan_scoreGood: "Сайн",
    tailan_scoreSatisfactory: "Хангалттай",
    tailan_scoreAverage: "Дунд",
    tailan_scoreInsufficient: "Хангалтгүй",
    tailan_dataProcessingNamePlaceholder: "Өгөгдөл боловсруулалтын нэр...",
  },
  en: {
    // Navigation & common
    settings: "Settings",
    logout: "Sign out",
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    delete: "Delete",
    edit: "Edit",
    search: "Search",
    close: "Close",
    confirm: "Confirm",

    // Settings page
    settingsTitle: "Settings",
    settingsSubtitle: "Profile and security settings",
    profileImage: "Profile photo",
    profileImageDesc: "Update your profile photo",
    changeImage: "Choose photo",
    removeImage: "Remove photo",
    imageSuccess: "Profile photo updated successfully",
    imageRemoved: "Profile photo removed",
    imageError: "Failed to save photo",
    imageTooBig: "Photo is too large. Please choose a smaller image.",
    imageHint1: "Maximum file size 5MB",
    imageHint2: "Automatically resized to 300x300",
    imageHint3: "JPG, PNG, GIF formats supported",

    changePassword: "Change password",
    changePasswordDesc: "Create a new password for security",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    currentPasswordPlaceholder: "Enter your current password",
    newPasswordPlaceholder: "Enter your new password",
    confirmPasswordPlaceholder: "Re-enter your new password",
    passwordRequirements: "Password requirements:",
    passwordReq1: "At least 8 characters",
    passwordReq2: "Contains uppercase letter (A-Z)",
    passwordReq3: "Contains lowercase letter (a-z)",
    passwordReq4: "Contains a number (0-9)",
    passwordReq5: "Contains special character (@$!%*?&#)",
    passwordChanging: "Changing...",
    passwordChanged: "Password changed successfully",
    passwordMismatch: "Passwords do not match",
    passwordInvalid: "Password does not meet requirements",
    passwordFillAll: "Please fill in all fields",
    passwordChangeBtn: "Change password",

    language: "Language",
    languageDesc: "Select the display language",
    mongolian: "Монгол",
    english: "English",

    // Navigation
    navHome: "Home",
    navDepartments: "Departments",
    navNews: "News",
    navTools: "Tools",
    navAdmin: "Admin",
    navAdminPanel: "Admin panel",
    navUsers: "Users",
    navTheme: "Theme",
    navProfileSettings: "Profile settings",

    // Common UI
    dashboard: "Dashboard",
    tools: "Tools",
    admin: "Admin",
    notifications: "Notifications",
    profile: "Profile",
    department: "Department",

    // Hero greetings
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    defaultEmployee: "Employee",
    defaultUser: "User",
    defaultDepartment: "Internal Audit Division",
    defaultPosition: "Data Engineer",
    loadingText: "Loading...",
    toolsButton: "Tools",

    // Auth
    needLogin: "Login required",
    needLoginToolsDesc: "Please sign in to use tools.",
    needLoginDeptDesc: "Please sign in to view this page.",

    // Tools page
    toolsPageTitle: "Tools",
    toolsPageSubtitle: "Internal Audit Division",
    toolsOpen: "Open",
    toolsFree: "Free tools",
    toolsWork: "Work tools",
    toolsNoneFound: "No tools found",
    toolsNoneDesc: "You don't have access to any tools. Contact your admin to request access.",
    toolTodoTitle: "To-do list",
    toolTodoDesc: "Plan and track your daily tasks efficiently",
    toolChessTitle: "Chess",
    toolChessDesc: "Chess game — play online with your teammates",
    toolSampleTitle: "Random sampling",
    toolSampleDesc: "Tool for generating random audit samples",
    toolPivotTitle: "Pivot",
    toolPivotDesc: "Create pivot tables from Excel files",
    toolReportTitle: "Quarterly report",
    toolReportDesc: "Prepare quarterly work reports",
    toolDbRequestTitle: "Request access",
    toolDbRequestDesc: "Request access to ClickHouse tables and manage your requests",
    toolDbGrantTitle: "Grant access",
    toolDbGrantDesc: "Review and manage ClickHouse access requests",
    toolEnglishTitle: "English vocabulary",
    toolEnglishDesc: "Build your English vocabulary and memorize with flashcards and tests",
    toolExcelTitle: "Excel report",
    toolExcelDesc: "Generate and download Excel reports from system data using dynamic Python code",
    toolPdfTitle: "PDF → Text",
    toolPdfDesc: "Convert PDF files to text and copy the content",
    toolDataDocTitle: "Data dictionary",
    toolDataDocDesc: "ClickHouse database structure, column descriptions, and code library",
    toolAlertBoxTitle: "Alert Box",
    toolAlertBoxDesc: "Transaction risk analysis, CIF search, and red-flag alerts",

    // Departments page
    albumTitle: "Album",
    addPhoto: "Add photo",
    uploadPhotoPrompt: "Upload team photos",
    photoSizeHint: "PNG, JPG, WEBP · max 3MB",
    photosSuffix: "photos",
    photoSizeError: "Photo must be less than 3MB",
    photoAdded: "Photo added",
    photoUploadError: "Failed to upload photo",
    deleteError: "Failed to delete",
    confirmDeletePhoto: "Delete this photo?",
    collapseText: "Show less",
    showMoreText: "Show more",
    activeStatus: "Active",
    inactiveStatus: "Inactive",
    managerBadge: "Manager",
    youBadge: "You",
    myDept: "My department",
    employeeSuffix: "employees",
    managerLabel: "Manager",
    missionTitle: "Mission",
    missionSubtitle: "Department's main objective",
    noDescription: "No description added. Admin can add this information.",
    teamTitle: "Team",
    teamSubtitle: "Department members",
    noEmployees: "No employees registered",
    otherDeptsTitle: "Other departments",
    otherDeptsSubtitle: "Organization structure",
    noOtherDepts: "No other departments found.",
    deptUnknownTitle: "Department not specified",
    deptUnknownDesc: "Your department has not been defined. Please contact your admin.",
    deptsLoadError: "Failed to load departments.",
    deptDetailLoadError: "Failed to load department details.",
    deptLoadError: "Failed to load department information.",

    // News page
    newsTitle: "News & Announcements",
    newsSubtitle: "DaHUB — Internal audit announcement system",
    latestNews: "Latest news",
    otherNews: "Other news",
    noNews: "No news available",
    readMore: "Read more",
    minRead: "min",
    minuteRead: "min read",
    newsLoading: "Loading news...",
    newsDefaultAuthor: "Internal Audit",
    internalAuditLabel: "Internal Audit — DAHUB",
    internalAuditDept: "Internal Audit Division",
    newsCreateTitle: "Add News",
    newsCreateBtn: "Publish",
    newsFormTitle: "Title",
    newsFormContent: "Content",
    newsFormCategory: "Category",
    newsFormImage: "Image",
    newsFormImageHint: "Upload image (up to 2MB)",
    newsCreateSuccess: "News published successfully!",
    newsCreateError: "Failed to add news",
    newsStatsTitle: "Top Publishers",
    newsStatsRank: "#",
    newsStatsAuthor: "Publisher",
    newsStatsCount: "News",
    newsStatsViews: "Total Views",
    newsStatsEmpty: "No data available yet",
    newsDelete: "Delete",
    newsDeleteConfirm: "Delete this news?",
    newsDeleteError: "Failed to delete news",

    // Tailan (Quarterly Report) tool
    tailan_loading: "Loading...",
    tailan_title: "Quarterly Report",
    tailan_subtitle: "Quarterly work report preparation and consolidation system",
    tailan_myReport: "My Report",
    tailan_privateTag: "Personal",
    tailan_myReportDesc: "Prepare and submit your report to the department head",
    tailan_deptReport: "Department Report",
    tailan_headTag: "Head",
    tailan_deptReportDesc: "Consolidate members' reports into one document",
    tailan_membersView: "View Members' Reports",
    tailan_viewTag: "View",
    tailan_membersViewDesc: "View submitted reports from department members",
    tailan_myReportTitle: "My Report",
    tailan_downloadWord: "Download Word",
    tailan_submitReport: "Submit",
    tailan_cyrillicName: "Name (Cyrillic)",
    tailan_cyrillicNamePlaceholder: "Enter your name as it will appear in the report",
    tailan_yearLabel: "Year",
    tailan_quarterLabel: "Quarter",
    tailan_s1Title: "I. Support for audit activities through data analysis results",
    tailan_s12Title: "I.2 Quality and results of newly developed Dashboard",
    tailan_s2Title: "II. Data processing tasks required for audit activities",
    tailan_s3Title: "III. Recurring tasks",
    tailan_s31Title: "III.1 Timely execution of data processing automation",
    tailan_s32Title: "III.2 Maintaining normal dashboard operations",
    tailan_s4Title: "IV. Training attended",
    tailan_s41Title: "IV.1 Application of knowledge gained from training",
    tailan_s5Title: "V. Assigned task completion",
    tailan_s6Title: "VI. Team activities",
    tailan_s7Title: "VII. New proposals and initiatives",
    tailan_dynTitle: "Additional sections (VIII, IX, …)",
    tailan_showInReport: "Show in report",
    tailan_hideFromReport: "Hide from report",
    tailan_addTask: "Add task",
    tailan_addEntry: "Add",
    tailan_addTraining: "Add training",
    tailan_addSection: "Add extra section",
    tailan_taskNameLabel: "Task name",
    tailan_taskDescLabel: "Completion /description/",
    tailan_detailedDescPlaceholder: "Write a detailed description...",
    tailan_taskNamePlaceholder: "Task name...",
    tailan_plannedTaskLabel: "Planned task",
    tailan_taskCompletionPct: "Task completion (%)",
    tailan_periodLabel: "Period completed",
    tailan_startDateLabel: "Start date",
    tailan_endDateLabel: "End date",
    tailan_taskSummaryLabel: "Completion /brief/",
    tailan_briefSummaryPlaceholder: "Brief description...",
    tailan_plannedTaskPlaceholder: "Planned task name...",
    tailan_autoTaskPlaceholder: "Recurring automation...",
    tailan_valueUsagePlaceholder: "Value/usage...",
    tailan_userRatingPlaceholder: "User rating (0-100)",
    tailan_dashboardNamePlaceholder: "Dashboard name...",
    tailan_clientRatingPlaceholder: "Client unit rating (0-100)",
    tailan_trainingNamePlaceholder: "Training name...",
    tailan_organizerLabel: "Organizer",
    tailan_trainingTypeLabel: "Training type",
    tailan_selectOption: "-- Select --",
    tailan_externalTraining: "External",
    tailan_internalTraining: "Internal",
    tailan_trainingFormatLabel: "Training format",
    tailan_onlineFormat: "Online",
    tailan_inPersonFormat: "In-person",
    tailan_hoursLabel: "Hours",
    tailan_meetsGoalLabel: "Meets audit goal",
    tailan_meetsGoalYes: "Yes",
    tailan_meetsGoalNo: "No",
    tailan_sharedKnowledgeLabel: "Shared knowledge",
    tailan_sharedKnowledgeYes: "Shared",
    tailan_sharedKnowledgeNo: "Not shared",
    tailan_knowledgeUsagePlaceholder: "How knowledge from training is being applied...",
    tailan_taskTypePlaceholder: "Task type...",
    tailan_completedWorkPlaceholder: "Completed work...",
    tailan_teamActivityPlaceholder: "Team activity...",
    tailan_initiativeLabel: "Initiative",
    tailan_proposalPlaceholder: "Write new proposals and ideas...",
    tailan_sectionTitlePlaceholder: "Section title...",
    tailan_sectionContentPlaceholder: "Section content...",
    tailan_livePreview: "Realtime preview — Word document",
    tailan_dateLabel: "Date",
    tailan_viewReportTitle: "View report",
    tailan_reportLoading: "Loading report...",
    tailan_noReportSubmitted: "has not submitted a report this quarter.",
    tailan_noReportsThisQuarter: "No reports registered for this quarter",
    tailan_submitted: "Submitted",
    tailan_draft: "Draft",
    tailan_submittedAtLabel: "Submitted:",
    tailan_updatedAtLabel: "Updated:",
    tailan_viewReportHint: "View report",
    tailan_deptReportPageTitle: "Department quarterly report",
    tailan_savingLabel: "Saving...",
    tailan_collapseSidebar: "Collapse",
    tailan_expandSidebar: "Expand",
    tailan_evalTitle: "Summary / Evaluation",
    tailan_totalScoreLabel: "Total score:",
    tailan_allSectionsOverview: "All sections overview",
    tailan_s1Label: "Board & Audit Committee Status",
    tailan_s2Label: "Customer Status",
    tailan_s3Label: "Internal Operations Status",
    tailan_s4Label: "Learning & Development Status",
    tailan_scorePointsSuffix: "pts",
    tailan_detailedEvalTable: "Detailed evaluation table",
    tailan_groupCol: "Group",
    tailan_keyIndicatorCol: "Key indicator",
    tailan_weightCol: "Weight",
    tailan_scoreCol: "Score",
    tailan_scoreDescCol: "Score description",
    tailan_subtotalRow: "Total",
    tailan_grandTotalRow: "TOTAL",
    tailan_signatureSection: "Signature",
    tailan_namePlaceholder: "Name...",
    tailan_titleJobPlaceholder: "/Title/",
    tailan_preparedBy: "PREPARED BY:",
    tailan_evaluatedBy: "EVALUATED & VALIDATED BY:",
    tailan_previewSection: "Preview",
    tailan_lastSavedLabel: "Last:",
    tailan_s4DetailedLabel: "Detailed description of training and development status:",
    tailan_s4DetailedPlaceholder: "Write in detail about training and development activities...",
    tailan_generalDescLabel: "General description",
    tailan_generalDescPlaceholder: "Write a detailed description of work and activities carried out within this perspective...",
    tailan_achievementsLabel: "Achievements and strengths",
    tailan_achievementsPlaceholder: "Note achievements, good results, and strengths during the reporting period...",
    tailan_challengesLabel: "Challenges",
    tailan_challengesPlaceholder: "Note challenges and issues requiring resolution during the reporting period...",
    tailan_widthLabel: "Width:",
    tailan_heightLabel: "Height:",
    tailan_addImageBtn: "+ Add image",
    tailan_noDataRow: "— No data —",
    tailan_productNamePlaceholder: "Product name...",
    tailan_sectionNamePlaceholder: "Section name...",
    tailan_importFromMyReportBtn: "Import from my report",
    tailan_descriptionTextLabel: "Description text",
    tailan_descriptionTextPlaceholder: "Description of resources and time saved during the reporting period...",
    tailan_dataProductCol: "DATA PRODUCT",
    tailan_productTypeCol: "PRODUCT TYPE",
    tailan_savedDaysCol: "PERSON-DAYS SAVED",
    tailan_noTasksMsg: "No tasks — click 'Import from my report' or '+'",
    tailan_clickToImportMsg: "Click the import button",
    tailan_plannedTasksCol: "Planned tasks (completed)",
    tailan_completionCol: "Task completion",
    tailan_periodCol: "Period completed",
    tailan_completionBriefCol: "Completion /brief/",
    tailan_dataProcessingCol: "Data processing",
    tailan_valueUsageCol: "Value and usage",
    tailan_clientRatingCol: "Client rating",
    tailan_avgRow: "Average",
    tailan_addRowBtn: "+ Add row",
    tailan_addTaskBtn: "+ Add task",
    tailan_imageWidthSettings: "Image width settings",
    tailan_unnamedTask: "(unnamed)",
    tailan_periodPlaceholder: "Period...",
    tailan_completionBriefPlaceholder: "Completion /brief/...",
    tailan_valueUsagePlaceholder2: "Value, usage...",
    tailan_ratingPlaceholder: "Rating...",
    tailan_group14New: "Data products newly introduced during the reporting period",
    tailan_group14Used: "Data products used in audit activities during the reporting period",
    tailan_recurringDataCol: "Recurring data processing",
    tailan_dashboardValueCol: "Dashboard value and usage",
    tailan_noItemsMsg: "No items — click '+ Add item'",
    tailan_itemTitlePlaceholder: "Title...",
    tailan_bulletTextPlaceholder: "Bullet text...",
    tailan_addBulletBtn: "+ Add bullet",
    tailan_addItemBtn: "+ Add item",
    tailan_employeeNamePlaceholder: "Employee name...",
    tailan_knowledgeAppliedPlaceholder: "Knowledge application description... (new lines will appear as bullets)",
    tailan_employeeCol: "Employee",
    tailan_trainingNameCol: "Training name",
    tailan_organizerCol: "Organizer",
    tailan_typeCol: "Type",
    tailan_dateCol: "Date",
    tailan_formatCol: "Format",
    tailan_hoursCol: "Hours",
    tailan_meetsAuditGoalCol: "Related to audit goal",
    tailan_sharedKnowledgeCol: "Knowledge shared",
    tailan_s43EmployeePlaceholder: "Employee...",
    tailan_s43TrainingPlaceholder: "Training...",
    tailan_s43OrganizerPlaceholder: "Organizer...",
    tailan_s43TypePlaceholder: "Type...",
    tailan_s43DatePlaceholder: "Date...",
    tailan_s43FormatPlaceholder: "Format...",
    tailan_s43HoursPlaceholder: "Hours...",
    tailan_s43MeetsPlaceholder: "Yes/No...",
    tailan_s43KnowledgePlaceholder: "Knowledge...",
    tailan_kpiIndicatorPlaceholder: "Indicator...",
    tailan_kpiEvaluationPlaceholder: "Description...",
    tailan_scoreExcellent: "Excellent",
    tailan_scoreGood: "Good",
    tailan_scoreSatisfactory: "Satisfactory",
    tailan_scoreAverage: "Average",
    tailan_scoreInsufficient: "Insufficient",
    tailan_dataProcessingNamePlaceholder: "Data processing name...",
  },
} as const;

export type TranslationKey = keyof typeof translations.mn;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "mn",
  setLanguage: () => {},
  t: (key) => translations.mn[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("mn");

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Language | null;
    if (saved === "mn" || saved === "en") setLanguageState(saved);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("lang", lang);
  };

  const t = (key: TranslationKey): string => translations[language][key];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
