"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

export type Language = "mn" | "en";

export const translations = {
  mn: {
    // Navigation & common
    logout: "Гарах",
    back: "Буцах",
    save: "Хадгалах",
    cancel: "Болих",
    loading: "Ачааллаж байна...",
    error: "Алдаа",
    success: "Амжилттай",
    delete: "Устгах",
    edit: "Засах",
    search: "Хайх",
    close: "Хаах",
    confirm: "Баталгаажуулах",

    // Profile image
    changeImage: "Зураг сонгох",
    removeImage: "Зураг устгах",
    imageSuccess: "Профайл зураг амжилттай солигдлоо",
    imageRemoved: "Профайл зураг устгагдлаа",
    imageError: "Зураг хадгалахад алдаа гарлаа",
    imageTooBig: "Зураг хэт том байна. Жижиг зураг сонгоно уу.",
    imageHint1: "Хамгийн ихдээ 5MB хэмжээтэй зураг",
    imageHint3: "JPG, PNG, GIF форматтай байх",

    // Password
    currentPassword: "Одоогийн нууц үг",
    newPassword: "Шинэ нууц үг",
    confirmPassword: "Нууц үг баталгаажуулах",
    currentPasswordPlaceholder: "Одоогийн нууц үгээ оруулна уу",
    newPasswordPlaceholder: "Шинэ нууц үгээ оруулна уу",
    confirmPasswordPlaceholder: "Нууц үгээ дахин оруулна уу",
    passwordReq1: "Хамгийн багадаа 8 тэмдэгт",
    passwordReq2: "Том үсэг агуулсан (A-Z)",
    passwordReq3: "Жижиг үсэг агуулсан (a-z)",
    passwordReq4: "Тоо агуулсан (0-9)",
    passwordReq5: "Тусгай тэмдэгт агуулсан (@$!%*?&#)",
    passwordChanged: "Нууц үг амжилттай солигдлоо",
    passwordMismatch: "Шинэ нууц үг таарахгүй байна",
    passwordInvalid: "Нууц үг шаардлагыг хангахгүй байна",
    passwordFillAll: "Бүх талбарыг бөглөнө үү",
    passwordChangeBtn: "Нууц үг солих",

    // Navigation
    navHome: "Нүүр",
    navDepartments: "Ажилтнууд",
    navNews: "Мэдлэг",
    navTools: "Хэрэгсэл",
    navAdmin: "Админ",
    navAdminPanel: "Админ самбар",
    navUsers: "Хэрэглэгч",
    navTheme: "Загвар",
    navProfileSettings: "Профайл тохиргоо",

    // Home / hero
    greetingMorning: "Өглөөний мэнд",
    greetingAfternoon: "Өдрийн мэнд",
    greetingEvening: "Оройн мэнд",
    defaultEmployee: "Ажилтан",
    defaultUser: "Хэрэглэгч",
    defaultDepartment: "Дотоод Аудитын Газар",
    defaultPosition: "Дата инженер",
    loadingText: "Ачаалж байна...",
    toolsButton: "Хэрэгсэл",

    // Auth
    needLogin: "Нэвтрэх шаардлагатай",
    needLoginToolsDesc: "Хэрэгслүүдийг ашиглахын тулд нэвтэрнэ үү.",

    // Tools page
    toolsPageTitle: "Хэрэгсэл",
    toolsPageSubtitle: "Дотоод аудитын газар",
    toolsOpen: "Нээх",
    toolsNoneFound: "Хэрэгсэл олдсонгүй",
    toolsNoneDesc:
      "Танд ашиглах боломжтой хэрэгсэл байхгүй байна. Админтай холбогдож эрх авна уу.",
    toolSampleTitle: "Санамсаргүй түүвэр",
    toolSampleDesc: "Аудитын санамсаргүй түүвэр гаргах хэрэгсэл",
    toolPivotTitle: "Pivot",
    toolPivotDesc: "Excel файлаас pivot хүснэгт үүсгэх",
    toolReportTitle: "Улирлын тайлан",
    toolReportDesc: "Улирлын ажлын тайлан бэлтгэх",
    toolDbRequestTitle: "Эрх Хүсэх",
    toolDbRequestDesc: "ClickHouse хүснэгтэд хандах эрх хүсэх",
    toolDbGrantTitle: "Эрх Олгох",
    toolDbGrantDesc: "ClickHouse хандалтын хүсэлтүүдийг хянаж удирдах",
    toolDataDocTitle: "Өгөгдлийн толь бичиг",
    toolDataDocDesc: "ClickHouse өгөгдлийн сангийн баганын тайлбар",
    toolAlertBoxTitle: "Alert Box",
    toolAlertBoxDesc:
      "Банкны эрсдэлийн шинжилгээ, CIF хайлт, Red Flag мэдэгдэл",
    toolRiskAssessmentTitle: "Салбарын эрсдэлийн үнэлгээ",
    toolRiskAssessmentDesc: "Сар бүрийн эрсдэлийн үнэлгээ",
    toolReportsTitle: "Тайлан татах",
    toolReportsDesc: "Дотоод хэрэглээний тайлан татах хэрэгсэл",

    // Departments page (public)
    noEmployees: "Ажилтан бүртгэгдээгүй байна",

    // News (medleg) page
    noNews: "Нийтлэл байхгүй байна",
    minRead: "мин",
    newsDefaultAuthor: "Дотоод аудитын алба",
    internalAuditDept: "Дотоод аудитын газар",
    newsCreateError: "Нийтлэл нэмэхэд алдаа гарлаа",
    newsDeleteConfirm: "Энэ нийтлэлийг устгах уу?",
    newsDeleteError: "Нийтлэл устгахад алдаа гарлаа",
    newsCommentPlaceholder: "Сэтгэгдэл бичих...",
    newsCommentEmpty: "Сэтгэгдэл байхгүй байна",
    newsCommentError: "Сэтгэгдэл нэмэхэд алдаа гарлаа",

    // Common tool UI
    accessDenied: "Эрх хязгаарлагдсан",
    accessDeniedMsg:
      "Та энэ хэрэгслийг ашиглах эрхгүй байна. Админтай холбогдоно уу.",
    viewGrouped: "Бүлэг",
    viewTable: "Хүснэгт",

    // Pivot tool
    pivotTitle: "Pivot түүвэр тооцоолох",
    pivotSubtitle:
      "Кодоор бүлэглэж жилээр pivot хийн, түүвэр тооцоолж Excel татах",
    pivotFileLabel: "Excel эсвэл CSV файл оруулах",
    pivotDropZone: "Файл чирж оруулах буюу дарж сонгох",
    pivotFileError: "Зөвхөн Excel (.xlsx, .xls) эсвэл CSV файл оруулна уу",
    pivotNoData: "Файлд хангалттай мэдээлэл байхгүй",
    pivotYearFilter: "Жилийн шүүлтүүр",
    pivotAllYears: "Бүх жил",
    pivotDateCol: "Огноон багана",
    pivotGroupCol: "Бүлэглэх багана",
    pivotPrefixLen: "Prefix урт",
    pivotConfError: "Итгэлцэл / Алдаа",
    pivotCreateBtn: "Pivot үүсгэх",
    pivotResultTitle: "Кодын бүлгээр pivot",
    pivotExportBtn: "Excel татах",

    // Data dictionary tool
    dataDocCodeLib: "Код сан",
    dataDocCodeSaved: "код хадгалагдсан",
    dataDocDbLabel: "Өгөгдлийн сан",
    dataDocSelectDb: "DB сонгох",
    dataDocSearchTable: "Хүснэгт хайх…",
    dataDocNoTables: "Хүснэгт олдсонгүй",
    dataDocSelectTableHint: "← Хүснэгт сонгоно уу",
    dataDocColName: "Баганын нэр",
    dataDocColType: "Төрөл",
    dataDocColDesc: "Тайлбар",
    dataDocFiltered: "Тайлбартай",
    dataDocUnfiltered: "Тайлбаргүй",
    dataDocSearchCol: "Багана хайх…",
    dataDocDescPlaceholder: "Тайлбар оруулах…",
    dataDocSaving: "Хадгалж байна…",
    dataDocSaveError: "Хадгалахад алдаа гарлаа",

    // Alert Box
    alertTitle: "Alert",
    alertSubtitle: "2+ Dashboard-д илэрсэн CIF-үүд",
    alertMinDash: "Хамгийн бага:",
    alertLoading: "12 Dashboard шалгаж байна...",
    alertCifSearch: "CIF хайх... (шууд Oracle-с хайна)",
    alertOracleSearching: "Oracle-с хайж байна...",
    alertTransactions: "гүйлгээ",
    alertTotalAmount: "нийт дүн",
    alertLoadingDetail: "Дэлгэрэнгүй ачааллаж байна...",
    alertRows: "мөр",
    alertNoResult: "Alert илэрсэнгүй",
    searchSubtitle: "12 Dashboard дээр CIF хайлт",
    searchLoading: "12 Dashboard хайж байна...",
    dashTitle: "Dashboards",
    dashSearchPlaceholder: "Dashboard хайх...",
    dashLoading: "Уншиж байна...",
    dashCifSearch: "CIF хайх...",
    dashOracleLoading: "Oracle-с татаж байна...",
    dashOracleError: "Oracle алдаа гарлаа",
    dashRetry: "Дахин оролдох",
    dashNoData: "Өгөгдөл олдсонгүй",
    dashNoResults: "Илэрц олдсонгүй",
    redflagTitle: "Red Flag",
    redflagSubtitle: "Event Chain дүрмийн илэрцүүд",
    redflagLoading: "12 Dashboard-ийн Event Chain шалгаж байна...",
    redflagTotalRules: "Нийт дүрэм",
    redflagActive: "Идэвхжсэн",
    redflagTotalMatches: "Нийт давхцал",
    redflagNoResult: "Илэрц олдсонгүй",

    // Random sampling
    sampleTitle: "Санамсаргүй түүвэр",
    sampleSubtitle: "Excel файлаас санамсаргүй дээж сонгох",
    samplePreparing: "Excel бэлтгэж байна...",
    sampleWait: "Түр хүлээнэ үү",
    sampleDesign: "Түүврийн дизайн",
    sampleConfidence: "Итгэлийн түвшин",
    sampleErrorMargin: "Алдааны марж (%)",
    sampleStdDev: "Стандарт хазайлт (σ)",
    sampleFileName: "Хадгалах файлын нэр",
    sampleSaveDialog: "Хадгалах цонх ашиглах",
    sampleUploadFile: "Excel файл оруулах",
    sampleDropZone: "Файл чирж оруулах буюу дарж сонгох",
    sampleFilterByCol: "Баганаар шүүх",
    sampleFilterCol: "Шүүх багана",
    sampleFilterValues: "Утгын шүүлтүүр",
    sampleSelectCol: "— Багана сонгоно —",
    sampleSearchValues: "Утга хайх...",
    sampleAllValues: "Бүх утга",
    sampleCollapse: "Хураах",
    sampleForceAll: "Бүх утгыг заавал хамруулах",
    sampleNoFilter: "⚠️ Сонгосон баганад илэрц олдсонгүй.",
    sampleSizeLabel: "Тооцоологдсон түүврийн хэмжээ",
    samplePopN: "Эх олонлогийн тоо (N)",
    sampleGroupN: "Бүлгийн тоо (≥2)",

    // Reports tool
    reportsSearchPlaceholder: "Хайх...",
    reportsLoadError: "Тайлан ачаалахад алдаа гарлаа",
    reportsNoAccess: "Эрхтэй тайлан байхгүй байна",
    reportsContactAdmin: "Администратортай холбогдоно уу",
    reportsTool: "тайлан",
    reportsDateInstant: "Шууд татах",
    reportsDateSingle: "Нэг огноо",
    reportsDateRange: "Хугацааны интервал",
    reportsToolNotFound: "Tool олдсонгүй",
    reportsToolLoadError: "Мэдээлэл татахад алдаа гарлаа",
    reportsDateRequired: "Огноо оруулна уу",
    reportsFilterRequired: "Заавал шүүлтүүр бөглөнө үү",
    reportsDownloadSuccess: "Амжилттай татлаа",
    reportsDownloadCanceled: "Таталтыг зогсооллоо",
    reportsPreviewCanceled: "Preview-г зогсооллоо",
    reportsDateRangeLabel: "Огнооны интервал",
    reportsDateStart: "Эхлэх",
    reportsDateEnd: "Дуусах",
    reportsDateSingleLabel: "Огноо",
    reportsDateNone: "Огноо шаардлагагүй",
    reportsFiltersLabel: "Шүүлтүүрүүд",
    reportsFilterRequiredMsg: "Заавал шаардлагатай",
    reportsDownloading: "Татаж байна...",
    reportsDownloadDone: "Дууслаа ✓",
    reportsStopBtn: "Зогсоох",
    reportsOutputExcel: "Excel татах",
    reportsOutputCsv: "CSV татах",
    reportsStatTotal: "Нийт мөр",
    reportsStatColumns: "Багана",
    reportsStatSize: "Хэмжээ",
    reportsStatRows: "мөр",
    reportsPreviewEmpty: "Preview хоосон байна",
    reportsPreviewEmptyHint: "Огноо сонгоод Preview дарна уу",
    reportsPreviewEmptyHintNoDate: "Preview товч дарна уу",
    reportsPreviewError: "Preview алдаа",
    reportsPreviewFirst: "эхний",
    reportsPreviewColumns: "багана",
    reportsPreviewTotal: "нийт",
    reportsSearchNotFound: "олдсонгүй",

    // DB Access (requester)
    dbAccessMyGrants: "Идэвхтэй эрхүүд",
    dbAccessManage: "Хүсэлт шийдвэрлэх",
    dbAccessLoadError: "Хүснэгтүүд ачаалахад алдаа гарлаа",
    dbAccessTableSearch: "Хүснэгт хайх...",
    dbAccessTableUnit: "хүснэгт",
    dbAccessSelectTableHint: "← Хүснэгт сонгоно уу",
    dbAccessSelectSection: "Хүснэгт сонгох",
    dbAccessExpirySection: "Хугацаа & Шалтгаан",
    dbAccessExpiryDate: "Дуусах огноо",
    dbAccessExpiryTime: "Дуусах цаг",
    dbAccessReason: "Шалтгаан (заавал)",
    dbAccessReasonPlaceholder: "Яагаад энэ эрх хэрэгтэй байгаагаа бичнэ үү...",
    dbAccessSubmitBtn: "Хүсэлт илгээх",
    dbAccessValidationTitle: "Сонголт хийнэ үү",
    dbAccessValidationNoTable: "Хамгийн багадаа нэг хүснэгт сонгоно уу",
    dbAccessValidationDate: "Огноо оруулна уу",
    dbAccessValidationDateRequired: "Эрхийн дуусах огноог заавал оруулна уу",
    dbAccessValidationReason: "Шалтгаан оруулна уу",
    dbAccessValidationReasonRequired: "Эрх хүссэн шалтгааныг заавал бичнэ үү",
    dbAccessValidationBadDate: "Буруу огноо",
    dbAccessValidationFutureDate: "Дуусах хугацаа ирээдүйд байх ёстой",
    dbAccessRequestSent: "Хүсэлт илгээгдлээ",
    dbAccessRequestSentMsg: "хүснэгтэд эрх хүсэх хүсэлт амжилттай илгээгдлээ",
    dbAccessRequestError: "Хүсэлт илгээхэд алдаа гарлаа",

    // DB Access (manage/grant)
    dbManagePendingTab: "Хүлээгдэж буй",
    dbManageAllTab: "Бүх хүсэлт",
    dbManageGrantsTab: "Хэрэглэгчийн эрхийн жагсаалт",
    dbManageNoPending: "Одоогоор баталгаажаагүй хүсэлт алга.",
    dbManageNoRequests: "Хүсэлт байхгүй",
    dbManageSentAt: "Илгээсэн:",
    dbManageValidUntil: "Хүчинтэй:",
    dbManageResolvedAt: "Шийдвэрлэсэн:",
    dbManageTables: "Хүснэгтүүд",
    dbManageGrantType: "Эрхийн төрөл",
    dbManageReasonLabel: "Шалтгаан",
    dbManageDecisionNote: "Тайлбар (заавал)",
    dbManageDecisionPlaceholder: "Шийдвэрийн тайлбар...",
    dbManageApprove: "Батлах",
    dbManageReject: "Татгалзах",
    dbManageResolveBtn: "Шийдвэрлэх",
    dbManageConfirmDelete: "Энэ хүсэлтийг бүрмөсөн устгах уу?",
    dbManageApproved: "Зөвшөөрлөө",
    dbManageRejected: "Татгалзлаа",
    dbManageActionError: "Үйлдэл амжилтгүй",
    dbManageDeleteError: "Устгахад алдаа гарлаа",
    dbManageHistoryConfirm:
      "Бүх шийдвэрлэгдсэн хүсэлтийн түүхийг устгах уу? (Хүлээгдэж байгаа хүсэлтүүд хэвээр үлдэна)",
    dbManageHistoryDeleted: "Түүх устгагдлаа",
    dbManageRevoked: "Эрх цуцлагдлаа",
    dbManageRevokeError: "Цуцлахад алдаа гарлаа",
    dbManageCleanError: "CH цэвэрлэхэд алдаа гарлаа",
    dbManageCleaned: "CH хандалт цэвэрлэгдлээ",
    dbManageStatusPending: "Хүлээгдэж байна",
    dbManageStatusApproved: "Зөвшөөрөгдсөн",
    dbManageStatusRejected: "Татгалзсан",
    dbManageTitle: "Хүсэлт шийдвэрлэх",
    dbManageSubtitle: "Хандалтын хүсэлтүүдийг удридах",
    dbManageSummary: "Нийт",
    dbManageGrantUnit: "эрх",
    dbManageUserUnit: "хэрэглэгч",
    dbManageRevokeBtn: "Цуцлах",
    myGrantsTitle: "Миний Идэвхтэй Эрхүүд",
    myGrantsSubtitle: "Одоогийн хандалтын зөвшөөрлүүд",
    myGrantsEmpty: "Идэвхтэй эрх байхгүй",
    myGrantsEmptyHint: "Эрх хүсэхийн тул хүсэлт илгээнэ үү",
    myGrantsRequestBtn: "Эрх хүсэх",
    myGrantsGrantedBy: "Олгосон:",
    myGrantsExpiresLabel: "Хаагдах:",
    myGrantsExpired: "Хугацаа дууссан",
    myGrantsDaysLeft: "өдөр үлдсэн",
    myGrantsCloseBtn: "Хаах",
    myGrantsCloseTitle: "Эрхийг хугацаанаас өмнө хаах",
    myGrantsChCreds: "ClickHouse Нэвтрэх мэдээлэл",
    myGrantsChUser: "Хэрэглэгч:",
    myGrantsChPassword: "Нууц үг:",
    myGrantsCopyUser: "Хэрэглэгч нэр",
    myGrantsCopyPwd: "Нууц үг",

    // Risk Assessment
    riskMonitorCardTitle: "Эрсдэлийн хяналт",
    riskDoAssessCardTitle: "Эрсдэлийн үнэлгээ хийх",
    riskBranchSubtitle: "Салбарын үнэлгээ",
    riskDetailSubtitle: "Мөр бүрийн дэлгэрэнгүй",
    riskSaveError: "Хадгалахад алдаа",
    riskSavePlaceholder: "Жишээ: 2025 Q4 Улирал",

    // Quarterly report (tailan)
    tailan_loading: "Уншиж байна…",
    tailan_title: "Улирлын тайлан",
    tailan_subtitle: "Улирлын ажлын тайлан бэлтгэх, нэгтгэх систем",
    tailan_myReport: "Өөрийн тайлан",
    tailan_privateTag: "Хувийн",
    tailan_myReportDesc: "Тайлангаа бэлтгэж хэлтсийн ахлагч руу илгээх",
    tailan_deptReport: "Хэлтсийн тайлан",
    tailan_headTag: "Ахлагч",
    tailan_deptReportDesc: "Гишүүдийн тайлануудыг нэгтгэж нэг баримт болгох",
    tailan_membersView: "Гишүүдийн тайлан харах",
    tailan_viewTag: "Харах",
    tailan_membersViewDesc: "Хэлтсийн гишүүдийн илгээсэн тайлануудыг харах",
    tailan_myReportTitle: "Миний тайлан",
    tailan_downloadWord: "Word татах",
    tailan_submitReport: "Илгээх",
    tailan_cyrillicName: "Нэр (кириллээр)",
    tailan_cyrillicNamePlaceholder: "Тайланд бичигдэх нэрээ оруулна уу",
    tailan_yearLabel: "Он",
    tailan_quarterLabel: "Улирал",
    tailan_s1Title:
      "I. Дата анализын үр дүнгээр аудитын үйл ажиллагааг дэмжсэн байдал",
    tailan_s12Title:
      "I.2 Шинээр хөгжүүлсэн Дашбоард хөгжүүлэлтийн чанар, үр дүн",
    tailan_s2Title:
      "II. Аудитын үйл ажиллагаанд шаардлагатай өгөгдөл боловсруулах ажил",
    tailan_s3Title: "III. Тогтмол хийгддэг ажлууд",
    tailan_s31Title:
      "III.1 Өгөгдөл боловсруулалт автоматжуулалтыг цаг хугацаанд нь гүйцэтгэсэн байдал",
    tailan_s32Title:
      "III.2 Дашбоардын хэвийн ажиллагааг хангаж ажилласан байдал",
    tailan_s4Title: "IV. Хамрагдсан сургалт",
    tailan_s41Title: "IV.1 Сургалтаас олж авсан мэдлэгээ ашиглаж буй байдал",
    tailan_s5Title: "V. Үүрэг даалгаврын биелэлт",
    tailan_s6Title: "VI. Хамт олны ажил",
    tailan_s7Title: "VII. Шинэ санал санаачилга",
    tailan_dynTitle: "Нэмэлт хэсгүүд (VIII, IX, …)",
    tailan_showInReport: "Тайланд харуулах",
    tailan_hideFromReport: "Тайлангаас нуух",
    tailan_addTask: "Ажил нэмэх",
    tailan_addEntry: "Нэмэх",
    tailan_addTraining: "Сургалт нэмэх",
    tailan_addSection: "Нэмэлт хэсэг нэмэх",
    tailan_taskNameLabel: "Ажлын нэр",
    tailan_taskDescLabel: "Гүйцэтгэл /тайлбар/",
    tailan_detailedDescPlaceholder: "Дэлгэрэнгүй тайлбар бичнэ үү...",
    tailan_taskNamePlaceholder: "Ажлын нэр...",
    tailan_plannedTaskLabel: "Төлөвлөгөөт ажил",
    tailan_taskCompletionPct: "Ажлын гүйцэтгэл (%)",
    tailan_periodLabel: "Хийгдсэн хугацаа",
    tailan_startDateLabel: "Эхлэх огноо",
    tailan_endDateLabel: "Дуусах огноо",
    tailan_taskSummaryLabel: "Гүйцэтгэл /товч/",
    tailan_briefSummaryPlaceholder: "Товч тайлбар...",
    tailan_plannedTaskPlaceholder: "Төлөвлөгөөт ажлын нэр...",
    tailan_autoTaskPlaceholder: "Тогтмол хийгддэг автоматжуулалт...",
    tailan_valueUsagePlaceholder: "Ач холбогдол/хэрэглээ...",
    tailan_userRatingPlaceholder: "Хэрэглэгчийн үнэлгээ (0-100)",
    tailan_dashboardNamePlaceholder: "Dashboard нэр...",
    tailan_clientRatingPlaceholder: "Хэрэглэгч нэгжийн үнэлгээ (0-100)",
    tailan_trainingNamePlaceholder: "Сургалтын нэр...",
    tailan_organizerLabel: "Зохион байгуулагч",
    tailan_trainingTypeLabel: "Сургалтын төрөл",
    tailan_selectOption: "-- Сонгох --",
    tailan_externalTraining: "Гадаад",
    tailan_internalTraining: "Дотоод",
    tailan_trainingFormatLabel: "Сургалтын хэлбэр",
    tailan_onlineFormat: "Онлайн",
    tailan_inPersonFormat: "Танхим",
    tailan_hoursLabel: "Цаг",
    tailan_meetsGoalLabel: "Аудитын зорилгод нийцсэн эсэх",
    tailan_meetsGoalYes: "Нийцсэн",
    tailan_meetsGoalNo: "Нийцээгүй",
    tailan_sharedKnowledgeLabel: "Мэдлэгээ хуваалцсан эсэх",
    tailan_sharedKnowledgeYes: "Хуваалцсан",
    tailan_sharedKnowledgeNo: "Хуваалцаагүй",
    tailan_knowledgeUsagePlaceholder:
      "Сургалтаас авсан мэдлэгийг хэрхэн ашиглаж байгаа тухай...",
    tailan_taskTypePlaceholder: "Ажлын төрөл...",
    tailan_completedWorkPlaceholder: "Хийгдсэн ажил...",
    tailan_teamActivityPlaceholder: "Хамт олны ажил...",
    tailan_initiativeLabel: "Санаачилга",
    tailan_proposalPlaceholder:
      "Шинэ санал санаачилга, дэвшүүлсэн санааг бичнэ үү...",
    tailan_sectionTitlePlaceholder: "Хэсгийн гарчиг...",
    tailan_sectionContentPlaceholder: "Хэсгийн агуулга...",
    tailan_livePreview: "Realtime preview — Word баримт",
    tailan_dateLabel: "Огноо",
    tailan_viewReportTitle: "Тайлан харах",
    tailan_reportLoading: "Тайлан ачааллаж байна…",
    tailan_noReportSubmitted: "энэ улиралд тайлан илгээгээгүй байна.",
    tailan_noReportsThisQuarter: "Энэ улиралд бүртгэсэн тайлан байхгүй",
    tailan_submitted: "Илгээсэн",
    tailan_draft: "Ноорог",
    tailan_submittedAtLabel: "Илгээсэн:",
    tailan_updatedAtLabel: "Шинэчилсэн:",
    tailan_viewReportHint: "Тайлан харах",
    tailan_deptReportPageTitle: "Хэлтсийн улирлын тайлан",
    tailan_savingLabel: "Хадгалаж байна...",
    tailan_collapseSidebar: "Хураах",
    tailan_expandSidebar: "Дэлгэх",
    tailan_evalTitle: "Нэгтгэл / Дүгнэлт",
    tailan_totalScoreLabel: "Нийт оноо:",
    tailan_allSectionsOverview: "Бүх төлөвийн нэгтгэл",
    tailan_s1Label: "ТУЗ болон аудитын хорооны төлөв",
    tailan_s2Label: "Харилцагчийн төлөв",
    tailan_s3Label: "Дотоод үйл ажиллагааны төлөв",
    tailan_s4Label: "Сургалт хөгжлийн төлөв",
    tailan_scorePointsSuffix: "оноо",
    tailan_detailedEvalTable: "Дэлгэрэнгүй үнэлгээний хүснэгт",
    tailan_groupCol: "Бүлэг",
    tailan_keyIndicatorCol: "Түлхүүр үзүүлэлт",
    tailan_weightCol: "Хувь",
    tailan_scoreCol: "Үнэлгээ",
    tailan_scoreDescCol: "Үнэлгээний тайлбар",
    tailan_subtotalRow: "Нийт",
    tailan_grandTotalRow: "НИЙТ",
    tailan_signatureSection: "Гарын үсэг",
    tailan_namePlaceholder: "Нэр...",
    tailan_titleJobPlaceholder: "/Албан тушаал/",
    tailan_preparedBy: "БОЛОВСРУУЛСАН:",
    tailan_evaluatedBy: "ҮНЭЛЖ, БАТАЛГААЖУУЛСАН:",
    tailan_previewSection: "Урьдчилан харах",
    tailan_lastSavedLabel: "Сүүлд:",
    tailan_generalDescLabel: "Ерөнхий тайлбар",
    tailan_generalDescPlaceholder:
      "Энэ тэлэвийн хүрээнд хийсэн ажил, үйл ажиллагааны талаар дэлгэрэнгүй тайлбар бичнэ...",
    tailan_achievementsLabel: "Амжилт, давуу тал",
    tailan_achievementsPlaceholder:
      "Тайлант хугацаанд гарсан амжилт, сайн үр дүн, давуу талыг тэмдэглэнэ...",
    tailan_challengesLabel: "Бэрхшээл, сорилт",
    tailan_challengesPlaceholder:
      "Тайлант хугацаанд тулгарсан бэрхшээл, шийдвэрлэх шаардлагатай асуудлуудыг тэмдэглэнэ...",
    tailan_widthLabel: "Өргөн:",
    tailan_heightLabel: "Өндөр:",
    tailan_addImageBtn: "+ Зураг нэмэх",
    tailan_noDataRow: "— Мэдээлэл байхгүй —",
    tailan_productNamePlaceholder: "Бүтээгдэхүүний нэр...",
    tailan_sectionNamePlaceholder: "Хэсгийн нэр...",
    tailan_importFromMyReportBtn: "Хувийн тайланаас татах",
    tailan_descriptionTextLabel: "Тайлбар текст",
    tailan_descriptionTextPlaceholder:
      "Тайлант хугацаанд хэмнэсэн нөөц, цаг хугацааны талаарх тайлбар...",
    tailan_dataProductCol: "ДАТА БҮТЭЭГДЭХҮҮН",
    tailan_productTypeCol: "БҮТЭЭГДЭХҮҮНИЙ ТӨРӨЛ",
    tailan_savedDaysCol: "ХЭМНЭСЭН ХҮН/ӨДӨР",
    tailan_plannedTasksCol: "Төлөвлөгөөт ажил (Дууссан ажлууд)",
    tailan_completionCol: "Ажлын гүйцэтгэл",
    tailan_periodCol: "Хийгдсэн хугацаа",
    tailan_completionBriefCol: "Гүйцэтгэл /товч/",
    tailan_dataProcessingCol: "Өгөгдөл боловсруулалт",
    tailan_valueUsageCol: "Ач холбогдол хэрэглээ",
    tailan_clientRatingCol: "Хэрэглэгч нэгжийн үнэлгээ",
    tailan_avgRow: "Дундаж",
    tailan_imageWidthSettings: "Зургуудын өргөн тохиргоо",
    tailan_unnamedTask: "(нэргүй)",
    tailan_periodPlaceholder: "Хугацаа...",
    tailan_completionBriefPlaceholder: "Гүйцэтгэл /товч/...",
    tailan_valueUsagePlaceholder2: "Ач холбогдол, хэрэглээ...",
    tailan_ratingPlaceholder: "Үнэлгээ...",
    tailan_s14NewProducts:
      "Тайлант хугацаанд шинээр нэвтрүүлсэн дата бүтээгдэхүүн",
    tailan_s14UsedProducts:
      "Тайлант хугацаанд аудитын үйл ажиллагаанд ашигласан дата бүтээгдэхүүн",
    tailan_recurringDataCol: "Тогтмол хийгддэг өгөгдөл боловсруулалт",
    tailan_dashboardValueCol: "Dashboard-ийн ач холбогдол хэрэглээ",
    tailan_noItemsHint: "Зүйл байхгүй — нэмэх товч дарна уу",
    tailan_itemTitlePlaceholder: "Гарчиг...",
    tailan_bulletTextPlaceholder: "Буллет текст...",
    tailan_addBulletBtn: "+ Буллет нэмэх",
    tailan_addItemBtn: "+ Зүйл нэмэх",
    tailan_employeeNamePlaceholder: "Ажилтаны нэр...",
    tailan_knowledgeAppliedPlaceholder:
      "Мэдлэг ашиглалтын тайлбар... (шинэ мөрөөнд буллет байдлаар харагдана)",
    tailan_employeeCol: "Ажилтан",
    tailan_trainingNameCol: "Сургалтын нэр",
    tailan_organizerCol: "Зохион байгуулагч",
    tailan_typeCol: "Төрөл",
    tailan_dateCol: "Огноо",
    tailan_formatCol: "Хэлбэр",
    tailan_hoursCol: "Цаг",
    tailan_meetsAuditGoalCol: "Аудитын зорилготой холбогдсон",
    tailan_sharedKnowledgeCol: "Мэдлэг хуваалцсан",
    tailan_s43EmployeePlaceholder: "Ажилтан...",
    tailan_s43TrainingPlaceholder: "Сургалт...",
    tailan_s43OrganizerPlaceholder: "Зохион байгуулагч...",
    tailan_s43TypePlaceholder: "Төрөл...",
    tailan_s43DatePlaceholder: "Огноо...",
    tailan_s43FormatPlaceholder: "Хэлбэр...",
    tailan_s43HoursPlaceholder: "Цаг...",
    tailan_s43MeetsPlaceholder: "Тийм/Үгүй...",
    tailan_s43KnowledgePlaceholder: "Мэдлэг...",
    tailan_kpiIndicatorPlaceholder: "Үзүүлэлт...",
    tailan_kpiEvaluationPlaceholder: "Тайлбар...",
    tailan_scoreExcellent: "Маш сайн",
    tailan_scoreGood: "Сайн",
    tailan_scoreSatisfactory: "Хангалттай",
    tailan_scoreAverage: "Дунд",
    tailan_scoreInsufficient: "Хангалтгүй",
    tailan_dataProcessingNamePlaceholder: "Өгөгдөл боловсруулалтын нэр...",
    tailan_imagesCount: "зураг",
    tailan_taskResultLabel: "Гүйцэтгэлийн үр дүн",
    tailan_taskDetailedPlaceholder: "Дэлгэрэнгүй тайлбар бичнэ үү...",
    tailan_deleteAction: "Устгах",
    tailan_addImage: "+ Зураг нэмэх",
    tailan_s14NewProducts2:
      "Тайлант хугацаанд шинээр нэвтрүүлсэн дата бүтээгдэхүүн",
    tailan_s14UsedProducts2: "Тайлант хугацаанд ашигласан дата бүтээгдэхүүн",
    tailan_noData: "Мэдээлэл байхгүй",
    tailan_fetchFromPersonal: "Хувийн тайланаас татах",
    tailan_descriptionText: "Тайлбар текст",
    tailan_s14ResourceSavedPlaceholder:
      "Хэмнэсэн нөөц, цаг хугацааны тайлбар...",
    tailan_plannedTaskCol: "Төлөвлөгөөт ажил",
    tailan_taskCompletionCol: "Ажлын гүйцэтгэл",
    tailan_taskPeriodCol: "Хугацаа",
    tailan_noTasksHint: "Ажил байхгүй — татах эсвэл нэмэх товч дарна уу",
    tailan_avgLabel: "Дундаж",
    tailan_unnamed: "(нэргүй)",
    tailan_usageSignificanceCol: "Ач холбогдол хэрэглээ",
    tailan_clientScoreCol: "Хэрэглэгч нэгжийн үнэлгээ",
    tailan_clickFetchHint: "Татах товч дарна уу",
    tailan_usagePlaceholder: "Ач холбогдол, хэрэглээ...",
    tailan_scorePlaceholder: "Үнэлгээ...",
    tailan_addRow: "+ Мөр нэмэх",
    tailan_taskNameHeader: "Ажлын нэр",
    tailan_completionPctHeader: "Гүйцэтгэл %",
    tailan_completionBriefHeader: "Гүйцэтгэл /товч/",
    tailan_periodHeader: "Хугацаа",
    tailan_regularDataProcessingCol: "Тогтмол хийгддэг өгөгдөл боловсруулалт",
    tailan_dashUsageCol: "Dashboard-ийн ач холбогдол хэрэглээ",
    tailan_dashNamePlaceholder: "Dashboard нэр...",
    tailan_titlePlaceholder: "Гарчиг...",
    tailan_deleteItemAction: "Зүйл устгах",
    tailan_addBullet: "+ Буллет нэмэх",
    tailan_addItem: "+ Зүйл нэмэх",
    tailan_s43employeeHeader: "Ажилтан",
    tailan_s43trainingHeader: "Сургалтын нэр",
    tailan_s43organizerHeader: "Зохион байгуулагч",
    tailan_s43typeHeader: "Төрөл",
    tailan_s43dateHeader: "Огноо",
    tailan_s43formatHeader: "Хэлбэр",
    tailan_s43hoursHeader: "Цаг",
    tailan_s43meetsGoalHeader: "Аудитын зорилготой холбогдсон",
    tailan_s43sharedHeader: "Мэдлэг хуваалцсан",
    tailan_s43employeePlaceholder: "Ажилтан...",
    tailan_s43trainingPlaceholder: "Сургалт...",
    tailan_s43organizerPlaceholder: "Зохион байгуулагч...",
    tailan_s43typePlaceholder: "Төрөл...",
    tailan_s43datePlaceholder: "Огноо...",
    tailan_s43formatPlaceholder: "Хэлбэр...",
    tailan_s43hoursPlaceholder: "Цаг...",
    tailan_s43meetsGoalPlaceholder: "Тийм/Үгүй...",
    tailan_s43sharedPlaceholder: "Мэдлэг...",
    tailan_keyIndicatorHeader: "Түлхүүр үзүүлэлт",
    tailan_weightPctHeader: "Хувь %",
    tailan_scoreHeader: "Үнэлгээ",
    tailan_evaluatedDescHeader: "Үнэлгээний тайлбар",
    tailan_s4ContentLabel: "Сургалт, хөгжлийн агуулга",
    tailan_s4ContentPlaceholder: "Сургалт, хөгжлийн агуулгыг бичнэ үү...",
  },
  en: {
    // Navigation & common
    logout: "Sign out",
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    delete: "Delete",
    edit: "Edit",
    search: "Search",
    close: "Close",
    confirm: "Confirm",

    // Profile image
    changeImage: "Choose photo",
    removeImage: "Remove photo",
    imageSuccess: "Profile photo updated",
    imageRemoved: "Profile photo removed",
    imageError: "Failed to save photo",
    imageTooBig: "Photo too large. Please choose a smaller image.",
    imageHint1: "Maximum file size 5 MB",
    imageHint3: "JPG, PNG, GIF formats supported",

    // Password
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    currentPasswordPlaceholder: "Enter your current password",
    newPasswordPlaceholder: "Enter your new password",
    confirmPasswordPlaceholder: "Re-enter your new password",
    passwordReq1: "At least 8 characters",
    passwordReq2: "Contains uppercase letter (A–Z)",
    passwordReq3: "Contains lowercase letter (a–z)",
    passwordReq4: "Contains a number (0–9)",
    passwordReq5: "Contains a special character (@$!%*?&#)",
    passwordChanged: "Password changed successfully",
    passwordMismatch: "Passwords do not match",
    passwordInvalid: "Password does not meet requirements",
    passwordFillAll: "Please fill in all fields",
    passwordChangeBtn: "Change password",

    // Navigation
    navHome: "Home",
    navDepartments: "Departments",
    navNews: "Knowledge",
    navTools: "Tools",
    navAdmin: "Admin",
    navAdminPanel: "Admin panel",
    navUsers: "Users",
    navTheme: "Theme",
    navProfileSettings: "Profile settings",

    // Home / hero
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    defaultEmployee: "Employee",
    defaultUser: "User",
    defaultDepartment: "Internal Audit Division",
    defaultPosition: "Data Engineer",
    loadingText: "Loading...",
    toolsButton: "Tools",

    // Auth
    needLogin: "Sign in required",
    needLoginToolsDesc: "Please sign in to use the tools.",

    // Tools page
    toolsPageTitle: "Tools",
    toolsPageSubtitle: "Internal Audit Division",
    toolsOpen: "Open",
    toolsNoneFound: "No tools available",
    toolsNoneDesc:
      "You don't have access to any tools. Contact your admin to request access.",
    toolSampleTitle: "Random Sampling",
    toolSampleDesc: "Generate random audit samples",
    toolPivotTitle: "Pivot",
    toolPivotDesc: "Create pivot tables from Excel files",
    toolReportTitle: "Quarterly Report",
    toolReportDesc: "Prepare quarterly work reports",
    toolDbRequestTitle: "Request Access",
    toolDbRequestDesc: "Request access to ClickHouse tables",
    toolDbGrantTitle: "Grant Access",
    toolDbGrantDesc: "Review and manage ClickHouse access requests",
    toolDataDocTitle: "Data Dictionary",
    toolDataDocDesc: "ClickHouse database column descriptions",
    toolAlertBoxTitle: "Alert Box",
    toolAlertBoxDesc:
      "Transaction risk analysis, CIF search, and Red Flag alerts",
    toolRiskAssessmentTitle: "Branch Risk Assessment",
    toolRiskAssessmentDesc: "Monthly branch risk assessment",
    toolReportsTitle: "Download Reports",
    toolReportsDesc: "Internal report download tool",

    // Departments page (public)
    noEmployees: "No employees registered",

    // News (medleg) page
    noNews: "No articles available",
    minRead: "min",
    newsDefaultAuthor: "Internal Audit",
    internalAuditDept: "Internal Audit Division",
    newsCreateError: "Failed to publish article",
    newsDeleteConfirm: "Delete this article?",
    newsDeleteError: "Failed to delete article",
    newsCommentPlaceholder: "Write a comment...",
    newsCommentEmpty: "No comments yet",
    newsCommentError: "Failed to add comment",

    // Common tool UI
    accessDenied: "Access restricted",
    accessDeniedMsg:
      "You don't have permission to use this tool. Contact your admin.",
    viewGrouped: "Group",
    viewTable: "Table",

    // Pivot tool
    pivotTitle: "Pivot & Sample Calculation",
    pivotSubtitle:
      "Group by code, pivot by year, calculate sample size and export to Excel",
    pivotFileLabel: "Upload Excel or CSV file",
    pivotDropZone: "Drag and drop or click to select a file",
    pivotFileError: "Please upload an Excel (.xlsx, .xls) or CSV file",
    pivotNoData: "Not enough data in file",
    pivotYearFilter: "Year filter",
    pivotAllYears: "All years",
    pivotDateCol: "Date column",
    pivotGroupCol: "Group column",
    pivotPrefixLen: "Prefix length",
    pivotConfError: "Confidence / Error",
    pivotCreateBtn: "Create pivot",
    pivotResultTitle: "Pivot by code group",
    pivotExportBtn: "Export to Excel",

    // Data dictionary tool
    dataDocCodeLib: "Code library",
    dataDocCodeSaved: "snippets saved",
    dataDocDbLabel: "Database",
    dataDocSelectDb: "Select DB",
    dataDocSearchTable: "Search tables…",
    dataDocNoTables: "No tables found",
    dataDocSelectTableHint: "← Select a table",
    dataDocColName: "Column name",
    dataDocColType: "Type",
    dataDocColDesc: "Description",
    dataDocFiltered: "With description",
    dataDocUnfiltered: "Without description",
    dataDocSearchCol: "Search columns…",
    dataDocDescPlaceholder: "Enter description…",
    dataDocSaving: "Saving…",
    dataDocSaveError: "Failed to save",

    // Alert Box
    alertTitle: "Alert",
    alertSubtitle: "CIFs appearing in 2+ dashboards",
    alertMinDash: "Minimum:",
    alertLoading: "Checking 12 dashboards...",
    alertCifSearch: "Search CIF... (direct Oracle lookup)",
    alertOracleSearching: "Searching Oracle...",
    alertTransactions: "transactions",
    alertTotalAmount: "total amount",
    alertLoadingDetail: "Loading details...",
    alertRows: "rows",
    alertNoResult: "No alerts found",
    searchSubtitle: "CIF search across 12 dashboards",
    searchLoading: "Searching 12 dashboards...",
    dashTitle: "Dashboards",
    dashSearchPlaceholder: "Search dashboards...",
    dashLoading: "Loading...",
    dashCifSearch: "Search CIF...",
    dashOracleLoading: "Fetching from Oracle...",
    dashOracleError: "Oracle error",
    dashRetry: "Retry",
    dashNoData: "No data found",
    dashNoResults: "No results found",
    redflagTitle: "Red Flag",
    redflagSubtitle: "Event chain rule matches",
    redflagLoading: "Checking event chains across 12 dashboards...",
    redflagTotalRules: "Total rules",
    redflagActive: "Active",
    redflagTotalMatches: "Total matches",
    redflagNoResult: "No matches found",

    // Random sampling
    sampleTitle: "Random Sampling",
    sampleSubtitle: "Select random samples from an Excel file",
    samplePreparing: "Preparing Excel...",
    sampleWait: "Please wait",
    sampleDesign: "Sample design",
    sampleConfidence: "Confidence level",
    sampleErrorMargin: "Error margin (%)",
    sampleStdDev: "Standard deviation (σ)",
    sampleFileName: "Output file name",
    sampleSaveDialog: "Use save dialog",
    sampleUploadFile: "Upload Excel file",
    sampleDropZone: "Drag and drop or click to select",
    sampleFilterByCol: "Filter by column",
    sampleFilterCol: "Filter column",
    sampleFilterValues: "Value filter",
    sampleSelectCol: "— Select column —",
    sampleSearchValues: "Search values...",
    sampleAllValues: "All values",
    sampleCollapse: "Collapse",
    sampleForceAll: "Force include all values",
    sampleNoFilter: "⚠️ No matches found in selected column.",
    sampleSizeLabel: "Calculated sample size",
    samplePopN: "Population size (N)",
    sampleGroupN: "Number of groups (≥ 2)",

    // Reports tool
    reportsSearchPlaceholder: "Search...",
    reportsLoadError: "Failed to load reports",
    reportsNoAccess: "No accessible reports",
    reportsContactAdmin: "Contact your administrator",
    reportsTool: "report(s)",
    reportsDateInstant: "Instant download",
    reportsDateSingle: "Single date",
    reportsDateRange: "Date range",
    reportsToolNotFound: "Tool not found",
    reportsToolLoadError: "Failed to load tool info",
    reportsDateRequired: "Please enter a date",
    reportsFilterRequired: "Please fill in required filters",
    reportsDownloadSuccess: "Download successful",
    reportsDownloadCanceled: "Download canceled",
    reportsPreviewCanceled: "Preview canceled",
    reportsDateRangeLabel: "Date range",
    reportsDateStart: "Start",
    reportsDateEnd: "End",
    reportsDateSingleLabel: "Date",
    reportsDateNone: "No date required",
    reportsFiltersLabel: "Filters",
    reportsFilterRequiredMsg: "Required",
    reportsDownloading: "Downloading...",
    reportsDownloadDone: "Done ✓",
    reportsStopBtn: "Stop",
    reportsOutputExcel: "Download Excel",
    reportsOutputCsv: "Download CSV",
    reportsStatTotal: "Total rows",
    reportsStatColumns: "Columns",
    reportsStatSize: "Size",
    reportsStatRows: "rows",
    reportsPreviewEmpty: "Preview is empty",
    reportsPreviewEmptyHint: "Select a date and click Preview",
    reportsPreviewEmptyHintNoDate: "Click the Preview button",
    reportsPreviewError: "Preview error",
    reportsPreviewFirst: "first",
    reportsPreviewColumns: "columns",
    reportsPreviewTotal: "total",
    reportsSearchNotFound: "not found",

    // DB Access (requester)
    dbAccessMyGrants: "Active grants",
    dbAccessManage: "Manage requests",
    dbAccessLoadError: "Failed to load tables",
    dbAccessTableSearch: "Search tables...",
    dbAccessTableUnit: "tables",
    dbAccessSelectTableHint: "← Select a table",
    dbAccessSelectSection: "Select tables",
    dbAccessExpirySection: "Expiry & Reason",
    dbAccessExpiryDate: "Expiry date",
    dbAccessExpiryTime: "Expiry time",
    dbAccessReason: "Reason (required)",
    dbAccessReasonPlaceholder: "Describe why you need this access...",
    dbAccessSubmitBtn: "Submit request",
    dbAccessValidationTitle: "Please make a selection",
    dbAccessValidationNoTable: "Select at least one table",
    dbAccessValidationDate: "Enter a date",
    dbAccessValidationDateRequired: "Expiry date is required",
    dbAccessValidationReason: "Enter a reason",
    dbAccessValidationReasonRequired:
      "Please provide a reason for your request",
    dbAccessValidationBadDate: "Invalid date",
    dbAccessValidationFutureDate: "Expiry date must be in the future",
    dbAccessRequestSent: "Request sent",
    dbAccessRequestSentMsg: "table access request(s) submitted successfully",
    dbAccessRequestError: "Failed to send request",

    // DB Access (manage/grant)
    dbManagePendingTab: "Pending",
    dbManageAllTab: "All requests",
    dbManageGrantsTab: "User grants",
    dbManageNoPending: "No pending requests.",
    dbManageNoRequests: "No requests",
    dbManageSentAt: "Sent:",
    dbManageValidUntil: "Valid until:",
    dbManageResolvedAt: "Resolved:",
    dbManageTables: "Tables",
    dbManageGrantType: "Grant type",
    dbManageReasonLabel: "Reason",
    dbManageDecisionNote: "Note (required)",
    dbManageDecisionPlaceholder: "Decision note...",
    dbManageApprove: "Approve",
    dbManageReject: "Reject",
    dbManageResolveBtn: "Resolve",
    dbManageConfirmDelete: "Permanently delete this request?",
    dbManageApproved: "Approved",
    dbManageRejected: "Rejected",
    dbManageActionError: "Action failed",
    dbManageDeleteError: "Failed to delete",
    dbManageHistoryConfirm:
      "Delete all resolved request history? (Pending requests will remain.)",
    dbManageHistoryDeleted: "History deleted",
    dbManageRevoked: "Access revoked",
    dbManageRevokeError: "Failed to revoke access",
    dbManageCleanError: "Failed to clean ClickHouse access",
    dbManageCleaned: "ClickHouse access cleaned up",
    dbManageStatusPending: "Pending",
    dbManageStatusApproved: "Approved",
    dbManageStatusRejected: "Rejected",
    dbManageTitle: "Manage Requests",
    dbManageSubtitle: "Review and manage access requests",
    dbManageSummary: "Total",
    dbManageGrantUnit: "grants",
    dbManageUserUnit: "users",
    dbManageRevokeBtn: "Revoke",
    myGrantsTitle: "My Active Grants",
    myGrantsSubtitle: "Current access permissions",
    myGrantsEmpty: "No active grants",
    myGrantsEmptyHint: "Submit a request to get access",
    myGrantsRequestBtn: "Request access",
    myGrantsGrantedBy: "Granted by:",
    myGrantsExpiresLabel: "Expires:",
    myGrantsExpired: "Expired",
    myGrantsDaysLeft: "days remaining",
    myGrantsCloseBtn: "Close",
    myGrantsCloseTitle: "Close grant early",
    myGrantsChCreds: "ClickHouse credentials",
    myGrantsChUser: "Username:",
    myGrantsChPassword: "Password:",
    myGrantsCopyUser: "Copy username",
    myGrantsCopyPwd: "Copy password",

    // Risk Assessment
    riskMonitorCardTitle: "Risk Monitoring",
    riskDoAssessCardTitle: "Run Risk Assessment",
    riskBranchSubtitle: "Branch assessment",
    riskDetailSubtitle: "Row-level detail",
    riskSaveError: "Failed to save",
    riskSavePlaceholder: "e.g. 2025 Q4",

    // Quarterly report (tailan)
    tailan_loading: "Loading…",
    tailan_title: "Quarterly Report",
    tailan_subtitle: "Quarterly work report — preparation and consolidation",
    tailan_myReport: "My Report",
    tailan_privateTag: "Personal",
    tailan_myReportDesc:
      "Prepare and submit your report to the department head",
    tailan_deptReport: "Department Report",
    tailan_headTag: "Head",
    tailan_deptReportDesc:
      "Consolidate members' reports into a single document",
    tailan_membersView: "View Members' Reports",
    tailan_viewTag: "View",
    tailan_membersViewDesc: "View reports submitted by department members",
    tailan_myReportTitle: "My Report",
    tailan_downloadWord: "Download Word",
    tailan_submitReport: "Submit",
    tailan_cyrillicName: "Name (Cyrillic)",
    tailan_cyrillicNamePlaceholder:
      "Enter your name as it will appear in the report",
    tailan_yearLabel: "Year",
    tailan_quarterLabel: "Quarter",
    tailan_s1Title: "I. Supporting audit activities through data analysis",
    tailan_s12Title: "I.2 Quality and outcomes of newly developed dashboards",
    tailan_s2Title: "II. Data processing tasks required for audit activities",
    tailan_s3Title: "III. Recurring tasks",
    tailan_s31Title: "III.1 Timely completion of data processing automation",
    tailan_s32Title: "III.2 Maintaining normal dashboard operations",
    tailan_s4Title: "IV. Training attended",
    tailan_s41Title: "IV.1 Applying knowledge gained from training",
    tailan_s5Title: "V. Assigned task completion",
    tailan_s6Title: "VI. Team activities",
    tailan_s7Title: "VII. New proposals and initiatives",
    tailan_dynTitle: "Additional sections (VIII, IX, …)",
    tailan_showInReport: "Show in report",
    tailan_hideFromReport: "Hide from report",
    tailan_addTask: "Add task",
    tailan_addEntry: "Add",
    tailan_addTraining: "Add training",
    tailan_addSection: "Add extra section",
    tailan_taskNameLabel: "Task name",
    tailan_taskDescLabel: "Completion / description",
    tailan_detailedDescPlaceholder: "Write a detailed description...",
    tailan_taskNamePlaceholder: "Task name...",
    tailan_plannedTaskLabel: "Planned task",
    tailan_taskCompletionPct: "Task completion (%)",
    tailan_periodLabel: "Period completed",
    tailan_startDateLabel: "Start date",
    tailan_endDateLabel: "End date",
    tailan_taskSummaryLabel: "Completion / brief",
    tailan_briefSummaryPlaceholder: "Brief summary...",
    tailan_plannedTaskPlaceholder: "Planned task name...",
    tailan_autoTaskPlaceholder: "Recurring automation task...",
    tailan_valueUsagePlaceholder: "Value / usage...",
    tailan_userRatingPlaceholder: "User rating (0–100)",
    tailan_dashboardNamePlaceholder: "Dashboard name...",
    tailan_clientRatingPlaceholder: "Client unit rating (0–100)",
    tailan_trainingNamePlaceholder: "Training name...",
    tailan_organizerLabel: "Organizer",
    tailan_trainingTypeLabel: "Training type",
    tailan_selectOption: "-- Select --",
    tailan_externalTraining: "External",
    tailan_internalTraining: "Internal",
    tailan_trainingFormatLabel: "Format",
    tailan_onlineFormat: "Online",
    tailan_inPersonFormat: "In-person",
    tailan_hoursLabel: "Hours",
    tailan_meetsGoalLabel: "Meets audit goal",
    tailan_meetsGoalYes: "Yes",
    tailan_meetsGoalNo: "No",
    tailan_sharedKnowledgeLabel: "Shared knowledge",
    tailan_sharedKnowledgeYes: "Shared",
    tailan_sharedKnowledgeNo: "Not shared",
    tailan_knowledgeUsagePlaceholder:
      "How you applied knowledge from this training...",
    tailan_taskTypePlaceholder: "Task type...",
    tailan_completedWorkPlaceholder: "Completed work...",
    tailan_teamActivityPlaceholder: "Team activity...",
    tailan_initiativeLabel: "Initiative",
    tailan_proposalPlaceholder: "Describe new proposals or ideas...",
    tailan_sectionTitlePlaceholder: "Section title...",
    tailan_sectionContentPlaceholder: "Section content...",
    tailan_livePreview: "Live preview — Word document",
    tailan_dateLabel: "Date",
    tailan_viewReportTitle: "View report",
    tailan_reportLoading: "Loading report…",
    tailan_noReportSubmitted: "has not submitted a report this quarter.",
    tailan_noReportsThisQuarter: "No reports submitted this quarter",
    tailan_submitted: "Submitted",
    tailan_draft: "Draft",
    tailan_submittedAtLabel: "Submitted:",
    tailan_updatedAtLabel: "Updated:",
    tailan_viewReportHint: "View report",
    tailan_deptReportPageTitle: "Department quarterly report",
    tailan_savingLabel: "Saving...",
    tailan_collapseSidebar: "Collapse",
    tailan_expandSidebar: "Expand",
    tailan_evalTitle: "Summary / Evaluation",
    tailan_totalScoreLabel: "Total score:",
    tailan_allSectionsOverview: "All sections overview",
    tailan_s1Label: "Board & Audit Committee",
    tailan_s2Label: "Customer perspective",
    tailan_s3Label: "Internal operations",
    tailan_s4Label: "Learning & development",
    tailan_scorePointsSuffix: "pts",
    tailan_detailedEvalTable: "Detailed evaluation table",
    tailan_groupCol: "Group",
    tailan_keyIndicatorCol: "Key indicator",
    tailan_weightCol: "Weight",
    tailan_scoreCol: "Score",
    tailan_scoreDescCol: "Score description",
    tailan_subtotalRow: "Subtotal",
    tailan_grandTotalRow: "GRAND TOTAL",
    tailan_signatureSection: "Signatures",
    tailan_namePlaceholder: "Name...",
    tailan_titleJobPlaceholder: "Title / Position",
    tailan_preparedBy: "PREPARED BY:",
    tailan_evaluatedBy: "REVIEWED AND APPROVED BY:",
    tailan_previewSection: "Preview",
    tailan_lastSavedLabel: "Saved:",
    tailan_generalDescLabel: "General description",
    tailan_generalDescPlaceholder:
      "Describe the work and activities carried out in this area...",
    tailan_achievementsLabel: "Achievements",
    tailan_achievementsPlaceholder:
      "Note key achievements and successes during this period...",
    tailan_challengesLabel: "Challenges",
    tailan_challengesPlaceholder:
      "Note challenges and issues that require resolution...",
    tailan_widthLabel: "Width:",
    tailan_heightLabel: "Height:",
    tailan_addImageBtn: "+ Add image",
    tailan_noDataRow: "— No data —",
    tailan_productNamePlaceholder: "Product name...",
    tailan_sectionNamePlaceholder: "Section name...",
    tailan_importFromMyReportBtn: "Import from my report",
    tailan_descriptionTextLabel: "Description",
    tailan_descriptionTextPlaceholder:
      "Describe resources and time saved during this period...",
    tailan_dataProductCol: "DATA PRODUCT",
    tailan_productTypeCol: "PRODUCT TYPE",
    tailan_savedDaysCol: "PERSON-DAYS SAVED",
    tailan_plannedTasksCol: "Planned tasks (completed)",
    tailan_completionCol: "Completion",
    tailan_periodCol: "Period",
    tailan_completionBriefCol: "Completion / brief",
    tailan_dataProcessingCol: "Data processing",
    tailan_valueUsageCol: "Value and usage",
    tailan_clientRatingCol: "Client rating",
    tailan_avgRow: "Average",
    tailan_imageWidthSettings: "Image width settings",
    tailan_unnamedTask: "(unnamed)",
    tailan_periodPlaceholder: "Period...",
    tailan_completionBriefPlaceholder: "Completion / brief...",
    tailan_valueUsagePlaceholder2: "Value, usage...",
    tailan_ratingPlaceholder: "Rating...",
    tailan_s14NewProducts: "New data products introduced during this period",
    tailan_s14UsedProducts:
      "Data products used in audit activities during this period",
    tailan_recurringDataCol: "Recurring data processing",
    tailan_dashboardValueCol: "Dashboard value and usage",
    tailan_noItemsHint: "No items — click the add button",
    tailan_itemTitlePlaceholder: "Title...",
    tailan_bulletTextPlaceholder: "Bullet text...",
    tailan_addBulletBtn: "+ Add bullet",
    tailan_addItemBtn: "+ Add item",
    tailan_employeeNamePlaceholder: "Employee name...",
    tailan_knowledgeAppliedPlaceholder:
      "Describe how you applied the knowledge (each line becomes a bullet point)",
    tailan_employeeCol: "Employee",
    tailan_trainingNameCol: "Training name",
    tailan_organizerCol: "Organizer",
    tailan_typeCol: "Type",
    tailan_dateCol: "Date",
    tailan_formatCol: "Format",
    tailan_hoursCol: "Hours",
    tailan_meetsAuditGoalCol: "Meets audit goal",
    tailan_sharedKnowledgeCol: "Knowledge shared",
    tailan_s43EmployeePlaceholder: "Employee...",
    tailan_s43TrainingPlaceholder: "Training...",
    tailan_s43OrganizerPlaceholder: "Organizer...",
    tailan_s43TypePlaceholder: "Type...",
    tailan_s43DatePlaceholder: "Date...",
    tailan_s43FormatPlaceholder: "Format...",
    tailan_s43HoursPlaceholder: "Hours...",
    tailan_s43MeetsPlaceholder: "Yes / No...",
    tailan_s43KnowledgePlaceholder: "Knowledge...",
    tailan_kpiIndicatorPlaceholder: "Indicator...",
    tailan_kpiEvaluationPlaceholder: "Description...",
    tailan_scoreExcellent: "Excellent",
    tailan_scoreGood: "Good",
    tailan_scoreSatisfactory: "Satisfactory",
    tailan_scoreAverage: "Average",
    tailan_scoreInsufficient: "Insufficient",
    tailan_dataProcessingNamePlaceholder: "Data processing name...",
    tailan_imagesCount: "images",
    tailan_taskResultLabel: "Task result",
    tailan_taskDetailedPlaceholder: "Write a detailed description...",
    tailan_deleteAction: "Delete",
    tailan_addImage: "+ Add image",
    tailan_s14NewProducts2: "New data products introduced during this period",
    tailan_s14UsedProducts2: "Data products used during this period",
    tailan_noData: "No data",
    tailan_fetchFromPersonal: "Import from my report",
    tailan_descriptionText: "Description",
    tailan_s14ResourceSavedPlaceholder: "Describe resources and time saved...",
    tailan_plannedTaskCol: "Planned task",
    tailan_taskCompletionCol: "Completion",
    tailan_taskPeriodCol: "Period",
    tailan_noTasksHint: "No tasks — click fetch or add",
    tailan_avgLabel: "Average",
    tailan_unnamed: "(unnamed)",
    tailan_usageSignificanceCol: "Value and usage",
    tailan_clientScoreCol: "Client score",
    tailan_clickFetchHint: "Click the fetch button",
    tailan_usagePlaceholder: "Value, usage...",
    tailan_scorePlaceholder: "Score...",
    tailan_addRow: "+ Add row",
    tailan_taskNameHeader: "Task name",
    tailan_completionPctHeader: "Completion %",
    tailan_completionBriefHeader: "Completion / brief",
    tailan_periodHeader: "Period",
    tailan_regularDataProcessingCol: "Recurring data processing",
    tailan_dashUsageCol: "Dashboard value and usage",
    tailan_dashNamePlaceholder: "Dashboard name...",
    tailan_titlePlaceholder: "Title...",
    tailan_deleteItemAction: "Delete item",
    tailan_addBullet: "+ Add bullet",
    tailan_addItem: "+ Add item",
    tailan_s43employeeHeader: "Employee",
    tailan_s43trainingHeader: "Training name",
    tailan_s43organizerHeader: "Organizer",
    tailan_s43typeHeader: "Type",
    tailan_s43dateHeader: "Date",
    tailan_s43formatHeader: "Format",
    tailan_s43hoursHeader: "Hours",
    tailan_s43meetsGoalHeader: "Meets audit goal",
    tailan_s43sharedHeader: "Knowledge shared",
    tailan_s43employeePlaceholder: "Employee...",
    tailan_s43trainingPlaceholder: "Training...",
    tailan_s43organizerPlaceholder: "Organizer...",
    tailan_s43typePlaceholder: "Type...",
    tailan_s43datePlaceholder: "Date...",
    tailan_s43formatPlaceholder: "Format...",
    tailan_s43hoursPlaceholder: "Hours...",
    tailan_s43meetsGoalPlaceholder: "Yes / No...",
    tailan_s43sharedPlaceholder: "Knowledge...",
    tailan_keyIndicatorHeader: "Key indicator",
    tailan_weightPctHeader: "Weight %",
    tailan_scoreHeader: "Score",
    tailan_evaluatedDescHeader: "Score description",
    tailan_s4ContentLabel: "Training & development content",
    tailan_s4ContentPlaceholder:
      "Describe training and development activities...",
  },
} as const;

export type TranslationKey = keyof typeof translations.mn;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "mn",
  setLanguage: () => {},
  t: (key) => translations.mn[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("mn");

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Language | null;
    if (saved === "mn" || saved === "en") setLanguageState(saved);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("lang", lang);
  };

  const t = (key: TranslationKey): string => translations[language][key];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
