"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  useMemo,
  ReactNode,
} from "react";

export type Language = "mn" | "en";

export const translations = {
  mn: {
    // Navigation & common
    logout: "Гарах",
    back: "Буцах",
    save: "Хадгалах",
    cancel: "Болих",
    loading: "Ачааллаж байна...",
    error: "Алдаа",
    success: "Амжилттай",
    // Settings page
    changeImage: "Зураг сонгох",
    removeImage: "Зураг устгах",
    imageSuccess: "Профайл зураг амжилттай солигдлоо",
    imageRemoved: "Профайл зураг устгагдлаа",
    imageError: "Зураг хадгалахад алдаа гарлаа",
    imageTooBig: "Зураг хэт том байна. Жижиг зураг сонгоно уу.",
    imageHint1: "Хамгийн их хэмжээ 5MB",
    imageHint3: "JPG, PNG, GIF формат дэмжигдэнэ",
    currentPassword: "Одоогийн нууц үг",
    newPassword: "Шинэ нууц үг",
    confirmPassword: "Нууц үг баталгаажуулах",
    currentPasswordPlaceholder: "Одоогийн нууц үгээ оруулна уу",
    newPasswordPlaceholder: "Шинэ нууц үгээ оруулна уу",
    confirmPasswordPlaceholder: "Нууц үгээ дахин оруулна уу",
    passwordReq1: "Хамгийн багадаа 8 тэмдэгт",
    passwordReq2: "Том үсэг агуулсан (A-Z)",
    passwordReq3: "Жижиг үсэг агуулсан (a-z)",
    passwordReq4: "Тоо агуулсан (0-9)",
    passwordReq5: "Тусгай тэмдэгт агуулсан (@$!%*?&#)",
    passwordMismatch: "Шинэ нууц үг таарахгүй байна",
    passwordInvalid: "Нууц үг шаардлагыг хангахгүй байна",
    passwordFillAll: "Бүх талбарыг бөглөнө үү",
    passwordChangeBtn: "Нууц үг солих",

    navHome: "Нүүр",
    navDepartments: "Хэлтэс",
    navEmployees: "Ажилтнууд",
    navNews: "Мэдлэг",
    navTools: "Хэрэгсэл",
    navAdmin: "Админ",
    navAdminPanel: "Админ самбар",
    navUsers: "Хэрэглэгч",
    navTheme: "Загвар",
    navProfileSettings: "Профайл тохиргоо",

    // Common UI
    needLogin: "Нэвтрэх шаардлагатай",
    needLoginToolsDesc: "Хэрэгслийг ашиглахын тулд нэвтэрнэ үү.",
    needLoginDeptDesc: "Энэ хуудсыг үзэхийн тулд нэвтэрнэ үү.",

    // Tools page
    toolsPageTitle: "Хэрэгсэл",
    toolsPageSubtitle: "Дотоод аудитын газар",
    toolsOpen: "Нээх",
    toolsNoneFound: "Хэрэгсэл олдсонгүй",
    toolsNoneDesc:
      "Танд ашиглах боломжтой хэрэгсэл байхгүй байна. Админтай холбогдож эрх авна уу.",
    toolSampleTitle: "Санамсаргүй түүвэр",
    toolSampleDesc: "Аудитын санамсаргүй түүвэр гаргах хэрэгсэл",
    toolPivotTitle: "Pivot",
    toolPivotDesc: "Excel файлаас pivot хүснэгт үүсгэх",
    toolReportTitle: "Улирлын тайлан",
    toolReportDesc: "Улирлын ажлын тайлан бэлтгэх",
    toolDbRequestTitle: "Эрх Хүсэх",
    toolDbRequestDesc: "ClickHouse хүснэгтэд хандах эрх хүсэх",
    toolDbGrantTitle: "Эрх Олгох",
    toolDbGrantDesc: "ClickHouse хандалтын хүсэлтүүдийг хянаж удирдах",
    toolDataDocTitle: "Өгөгдлийн толь бичиг",
    toolDataDocDesc: "ClickHouse өгөгдлийн сангийн баганын тайлбар",
    toolAlertBoxTitle: "Alert Box",
    toolAlertBoxDesc:
      "Банкны эрсдэлийн шинжилгээ, CIF хайлт, Red Flag мэдэгдэл",
    toolRiskAssessmentTitle: "Салбарын эрсдэлийн үнэлгээ",
    toolRiskAssessmentDesc: "Сар бүрийн эрсдэлийн үнэлгээ",
    toolReportsTitle: "Тайлан татах",
    toolReportsDesc: "Дотоод хэрэглээний тайлан татах хэрэгсэл",

    // Departments page
    managerBadge: "Дарга",
    youBadge: "Та",
    noEmployees: "Ажилтан бүртгэгдээгүй байна",
    deptsLoadError: "Хэлтсүүдийн жагсаалт ачаалахад алдаа гарлаа.",
    noNews: "Нийтлэл байхгүй байна",
    minRead: "мин",
    newsDefaultAuthor: "Дотоод аудитын алба",
    internalAuditDept: "Дотоод аудитын газар",
    newsCreateError: "Нийтлэл нэмэхэд алдаа гарлаа",
    newsDeleteConfirm: "Энэ нийтлэлийг устгах уу?",
    newsDeleteError: "Нийтлэл устгахад алдаа гарлаа",
    newsCommentPlaceholder: "Сэтгэгдэл бичих...",
    newsCommentEmpty: "Сэтгэгдэл байхгүй байна",
    newsCommentError: "Сэтгэгдэл нэмэхэд алдаа гарлаа",
    // Tailan (Quarterly Report) tool
    tailan_title: "Улирлын тайлан",
    tailan_myReport: "Өөрийн тайлан",
    tailan_deptReport: "Хэлтсийн тайлан",
    tailan_membersView: "Гишүүдийн тайлан харах",
    tailan_membersViewDesc: "Хэлтсийн гишүүдийн илгээсэн тайлануудыг харах",
    tailan_myReportTitle: "Миний тайлан",
    tailan_downloadWord: "Word татах",
    tailan_submitReport: "Илгээх",
    tailan_cyrillicName: "Нэр (кириллээр)",
    tailan_cyrillicNamePlaceholder: "Тайланд бичигдэх нэрээ оруулна уу",
    tailan_yearLabel: "Он",
    tailan_quarterLabel: "Улирал",
    tailan_s1Title:
      "I. Дата анализын үр дүнгээр аудитын үйл ажиллагааг дэмжсэн байдал",
    tailan_s12Title:
      "I.2 Шинээр хөгжүүлсэн Дашбоард хөгжүүлэлтийн чанар, үр дүн",
    tailan_s2Title:
      "II. Аудитын үйл ажиллагаанд шаардлагатай өгөгдөл боловсруулах ажил",
    tailan_s3Title: "III. Тогтмол хийгддэг ажлууд",
    tailan_s31Title:
      "III.1 Өгөгдөл боловсруулалт автоматжуулалтыг цаг хугацаанд нь гүйцэтгэсэн байдал",
    tailan_s32Title:
      "III.2 Дашбоардын хэвийн ажиллагааг хангаж ажилласан байдал",
    tailan_s4Title: "IV. Хамрагдсан сургалт",
    tailan_s41Title: "IV.1 Сургалтаас олж авсан мэдлэгээ ашиглаж буй байдал",
    tailan_s5Title: "V. Үүрэг даалгаврын биелэлт",
    tailan_s6Title: "VI. Хамт олны ажил",
    tailan_s7Title: "VII. Шинэ санал санаачилга",
    tailan_dynTitle: "Нэмэлт хэсгүүд (VIII, IX, …)",
    tailan_showInReport: "Тайланд харуулах",
    tailan_hideFromReport: "Тайлангаас нуух",
    tailan_addTask: "Ажил нэмэх",
    tailan_addEntry: "Нэмэх",
    tailan_addTraining: "Сургалт нэмэх",
    tailan_addSection: "Нэмэлт хэсэг нэмэх",
    tailan_taskNameLabel: "Ажлын нэр",
    tailan_taskDescLabel: "Гүйцэтгэл /тайлбар/",
    tailan_detailedDescPlaceholder: "Дэлгэрэнгүй тайлбар бичнэ үү...",
    tailan_taskNamePlaceholder: "Ажлын нэр...",
    tailan_plannedTaskLabel: "Төлөвлөгөөт ажил",
    tailan_taskCompletionPct: "Ажлын гүйцэтгэл (%)",
    tailan_periodLabel: "Хийгдсэн хугацаа",
    tailan_startDateLabel: "Эхлэх огноо",
    tailan_endDateLabel: "Дуусах огноо",
    tailan_taskSummaryLabel: "Гүйцэтгэл /товч/",
    tailan_briefSummaryPlaceholder: "Товч тайлбар...",
    tailan_plannedTaskPlaceholder: "Төлөвлөгөөт ажлын нэр...",
    tailan_autoTaskPlaceholder: "Тогтмол хийгддэг автоматжуулалт...",
    tailan_valueUsagePlaceholder: "Ач холбогдол/хэрэглээ...",
    tailan_userRatingPlaceholder: "Хэрэглэгчийн үнэлгээ (0-100)",
    tailan_dashboardNamePlaceholder: "Dashboard нэр...",
    tailan_clientRatingPlaceholder: "Хэрэглэгч нэгжийн үнэлгээ (0-100)",
    tailan_trainingNamePlaceholder: "Сургалтын нэр...",
    tailan_organizerLabel: "Зохион байгуулагч",
    tailan_trainingTypeLabel: "Сургалтын төрөл",
    tailan_selectOption: "-- Сонгох --",
    tailan_externalTraining: "Гадаад",
    tailan_internalTraining: "Дотоод",
    tailan_trainingFormatLabel: "Сургалтын хэлбэр",
    tailan_onlineFormat: "Онлайн",
    tailan_inPersonFormat: "Танхим",
    tailan_hoursLabel: "Цаг",
    tailan_meetsGoalLabel: "Аудитын зорилгод нийцсэн эсэх",
    tailan_meetsGoalYes: "Нийцсэн",
    tailan_meetsGoalNo: "Нийцээгүй",
    tailan_sharedKnowledgeLabel: "Мэдлэгээ хуваалцсан эсэх",
    tailan_sharedKnowledgeYes: "Хуваалцсан",
    tailan_sharedKnowledgeNo: "Хуваалцаагүй",
    tailan_knowledgeUsagePlaceholder:
      "Сургалтаас авсан мэдлэгийг хэрхэн ашиглаж байгаа тухай...",
    tailan_teamActivityPlaceholder: "Хамт олны ажил...",
    tailan_initiativeLabel: "Санаачилга",
    tailan_proposalPlaceholder:
      "Шинэ санал санаачилга, дэвшүүлсэн санааг бичнэ үү...",
    tailan_sectionTitlePlaceholder: "Хэсгийн гарчиг...",
    tailan_sectionContentPlaceholder: "Хэсгийн агуулга...",
    tailan_livePreview: "Realtime preview — Word баримт",
    tailan_dateLabel: "Огноо",
    tailan_viewReportTitle: "Тайлан харах",
    tailan_reportLoading: "Тайлан ачааллаж байна…",
    tailan_noReportSubmitted: "энэ улиралд тайлан илгээгээгүй байна.",
    tailan_noReportsThisQuarter: "Энэ улиралд бүртгэсэн тайлан байхгүй",
    tailan_submitted: "Илгээсэн",
    tailan_draft: "Ноорог",
    tailan_submittedAtLabel: "Илгээсэн:",
    tailan_updatedAtLabel: "Шинэчилсэн:",
    tailan_viewReportHint: "Тайлан харах",
    tailan_deptReportPageTitle: "Хэлтсийн улирлын тайлан",
    tailan_savingLabel: "Хадгалаж байна...",
    tailan_collapseSidebar: "Хураах",
    tailan_expandSidebar: "Дэлгэх",
    tailan_evalTitle: "Нэгтгэл / Дүгнэлт",
    tailan_totalScoreLabel: "Нийт оноо:",
    tailan_allSectionsOverview: "Бүх төлөвийн нэгтгэл",
    tailan_s1Label: "ТУЗ болон аудитын хорооны төлөв",
    tailan_s2Label: "Харилцагчийн төлөв",
    tailan_s3Label: "Дотоод үйл ажиллагааны төлөв",
    tailan_s4Label: "Сургалт хөгжлийн төлөв",
    tailan_scorePointsSuffix: "оноо",
    tailan_detailedEvalTable: "Дэлгэрэнгүй үнэлгээний хүснэгт",
    tailan_groupCol: "Бүлэг",
    tailan_keyIndicatorCol: "Түлхүүр үзүүлэлт",
    tailan_weightCol: "Хувь",
    tailan_scoreCol: "Үнэлгээ",
    tailan_scoreDescCol: "Үнэлгээний тайлбар",
    tailan_subtotalRow: "Нийт",
    tailan_grandTotalRow: "НИЙТ",
    tailan_signatureSection: "Гарын үсэг",
    tailan_namePlaceholder: "Нэр...",
    tailan_titleJobPlaceholder: "/Албан тушаал/",
    tailan_preparedBy: "БОЛОВСРУУЛСАН:",
    tailan_evaluatedBy: "ҮНЭЛЖ, БАТАЛГААЖУУЛСАН:",
    tailan_previewSection: "Урьдчилан харах",
    tailan_lastSavedLabel: "Сүүлд:",
    tailan_generalDescLabel: "Ерөнхий тайлбар",
    tailan_generalDescPlaceholder:
      "Энэ төлөвийн хүрээнд хийсэн ажил, үйл ажиллагааны талаар дэлгэрэнгүй тайлбар бичнэ...",
    tailan_achievementsLabel: "Амжилт, давуу тал",
    tailan_achievementsPlaceholder:
      "Тайлант хугацаанд гарсан амжилт, сайн үр дүн, давуу талыг тэмдэглэнэ...",
    tailan_challengesLabel: "Бэрхшээл, сорилт",
    tailan_challengesPlaceholder:
      "Тайлант хугацаанд тулгарсан бэрхшээл, шийдвэрлэх шаардлагатай асуудлуудыг тэмдэглэнэ...",
    tailan_widthLabel: "Өргөн:",
    tailan_heightLabel: "Өндөр:",
    tailan_productNamePlaceholder: "Бүтээгдэхүүний нэр...",
    tailan_sectionNamePlaceholder: "Хэсгийн нэр...",
    tailan_dataProductCol: "ДАТА БҮТЭЭГДЭХҮҮН",
    tailan_productTypeCol: "БҮТЭЭГДЭХҮҮНИЙ ТӨРӨЛ",
    tailan_savedDaysCol: "ХЭМНЭСЭН ХҮН/ӨДӨР",
    tailan_completionBriefCol: "Гүйцэтгэл /товч/",
    tailan_dataProcessingCol: "Өгөгдөл боловсруулалт",
    tailan_imageWidthSettings: "Зургуудын өргөн тохиргоо",
    tailan_periodPlaceholder: "Хугацаа...",
    tailan_completionBriefPlaceholder: "Гүйцэтгэл /товч/...",
    tailan_bulletTextPlaceholder: "Буллет текст...",
    tailan_employeeNamePlaceholder: "Ажилтны нэр...",
    tailan_kpiIndicatorPlaceholder: "Үзүүлэлт...",
    tailan_kpiEvaluationPlaceholder: "Тайлбар...",
    tailan_scoreExcellent: "Маш сайн",
    tailan_scoreGood: "Сайн",
    tailan_scoreSatisfactory: "Хангалттай",
    tailan_scoreAverage: "Дунд",
    tailan_scoreInsufficient: "Хангалтгүй",
    tailan_dataProcessingNamePlaceholder: "Өгөгдөл боловсруулалтын нэр...",
    tailan_imagesCount: "зураг",
    tailan_taskResultLabel: "Гүйцэтгэлийн үр дүн",
    tailan_taskDetailedPlaceholder: "Дэлгэрэнгүй тайлбар бичнэ үү...",
    tailan_deleteAction: "Устгах",
    tailan_addImage: "+ Зураг нэмэх",
    tailan_s14NewProducts:
      "Тайлант хугацаанд шинээр нэвтрүүлсэн дата бүтээгдэхүүн",
    tailan_s14UsedProducts: "Тайлант хугацаанд ашигласан дата бүтээгдэхүүн",
    tailan_noData: "Мэдээлэл байхгүй",
    tailan_fetchFromPersonal: "Хувийн тайланаас татах",
    tailan_descriptionText: "Тайлбар текст",
    tailan_s14ResourceSavedPlaceholder:
      "Хэмнэсэн нөөц, цаг хугацааны тайлбар...",
    tailan_plannedTaskCol: "Төлөвлөгөөт ажил",
    tailan_taskCompletionCol: "Ажлын гүйцэтгэл",
    tailan_taskPeriodCol: "Хийгдсэн хугацаа",
    tailan_noTasksHint: "Ажил байхгүй — татах эсвэл нэмэх товч дарна уу",
    tailan_avgLabel: "Дундаж",
    tailan_unnamed: "(нэргүй)",
    tailan_usageSignificanceCol: "Ач холбогдол хэрэглээ",
    tailan_clientScoreCol: "Хэрэглэгч нэгжийн үнэлгээ",
    tailan_clickFetchHint: "Татах товч дарна уу",
    tailan_usagePlaceholder: "Ач холбогдол, хэрэглээ...",
    tailan_scorePlaceholder: "Үнэлгээ...",
    tailan_addRow: "+ Мөр нэмэх",
    tailan_taskNameHeader: "Ажлын нэр",
    tailan_completionPctHeader: "Гүйцэтгэл %",
    tailan_completionBriefHeader: "Гүйцэтгэл /товч/",
    tailan_periodHeader: "Хугацаа",
    tailan_regularDataProcessingCol: "Тогтмол хийгддэг өгөгдөл боловсруулалт",
    tailan_dashUsageCol: "Dashboard-ийн ач холбогдол хэрэглээ",
    tailan_dashNamePlaceholder: "Dashboard нэр...",
    tailan_noItemsHint: "Зүйл байхгүй — нэмэх товч дарна уу",
    tailan_titlePlaceholder: "Гарчиг...",
    tailan_deleteItemAction: "Зүйл устгах",
    tailan_addBullet: "+ Буллет нэмэх",
    tailan_addItem: "+ Зүйл нэмэх",
    tailan_s43employeeHeader: "Ажилтан",
    tailan_s43trainingHeader: "Сургалтын нэр",
    tailan_s43organizerHeader: "Зохион байгуулагч",
    tailan_s43typeHeader: "Төрөл",
    tailan_s43dateHeader: "Огноо",
    tailan_s43formatHeader: "Хэлбэр",
    tailan_s43hoursHeader: "Цаг",
    tailan_s43meetsGoalHeader: "Аудитын зорилготой холбогдсон",
    tailan_s43sharedHeader: "Мэдлэг хуваалцсан",
    tailan_s43employeePlaceholder: "Ажилтан...",
    tailan_s43trainingPlaceholder: "Сургалт...",
    tailan_s43organizerPlaceholder: "Зохион байгуулагч...",
    tailan_s43typePlaceholder: "Төрөл...",
    tailan_s43datePlaceholder: "Огноо...",
    tailan_s43formatPlaceholder: "Хэлбэр...",
    tailan_s43hoursPlaceholder: "Цаг...",
    tailan_s43meetsGoalPlaceholder: "Тийм/Үгүй...",
    tailan_s43sharedPlaceholder: "Мэдлэг...",
    tailan_keyIndicatorHeader: "Түлхүүр үзүүлэлт",
    tailan_weightPctHeader: "Хувь %",
    tailan_scoreHeader: "Үнэлгээ",
    tailan_evaluatedDescHeader: "Үнэлгээний тайлбар",
    tailan_s4ContentLabel: "Сургалт, хөгжлийн агуулга",
    tailan_s4ContentPlaceholder: "Сургалт, хөгжлийн агуулгыг бичнэ үү...",

    // Common / shared UI
    accessDenied: "Эрх хязгаарлагдсан",
    accessDeniedMsg:
      "Та энэ хэрэгслийг ашиглах эрхгүй байна. Админтай холбогдоно уу.",
    viewGrouped: "Бүлэг",
    viewTable: "Хүснэгт",
    // Pivot tool
    pivotTitle: "Pivot түүвэр тооцоолох",
    pivotSubtitle:
      "Кодоор бүлэглэж жилээр pivot хийн, түүвэр тооцоолж Excel татах",
    pivotFileLabel: "Excel эсвэл CSV файл оруулах",
    pivotDropZone: "Файл чирж оруулах буюу дарж сонгох",
    pivotFileError: "Зөвхөн Excel (.xlsx, .xls) эсвэл CSV файл оруулна уу",
    pivotNoData: "Файлд хангалттай мэдээлэл байхгүй",
    pivotYearFilter: "Жилийн шүүлтүүр",
    pivotAllYears: "Бүх жил",
    pivotDateCol: "Огноон багана",
    pivotGroupCol: "Бүлэглэх багана",
    pivotPrefixLen: "Prefix урт",
    pivotConfError: "Итгэлцэл / Алдаа",
    pivotCreateBtn: "Pivot үүсгэх",
    pivotResultTitle: "Кодын бүлгээр pivot",
    pivotExportBtn: "Excel татах",

    // Data dictionary tool
    dataDocCodeLib: "Код сан",
    dataDocCodeSaved: "код хадгалагдсан",
    dataDocDbLabel: "Өгөгдлийн сан",
    dataDocSelectDb: "DB сонгох",
    dataDocSearchTable: "Хүснэгт хайх…",
    dataDocNoTables: "Хүснэгт олдсонгүй",
    dataDocSelectTableHint: "← Хүснэгт сонгоно уу",
    dataDocColName: "Баганын нэр",
    dataDocColType: "Төрөл",
    dataDocColDesc: "Тайлбар",
    dataDocFiltered: "Тайлбартай",
    dataDocUnfiltered: "Тайлбаргүй",
    dataDocSearchCol: "Багана хайх…",
    dataDocDescPlaceholder: "Тайлбар оруулах…",
    dataDocSaving: "Хадгалж байна…",
    dataDocSaveError: "Хадгалахад алдаа гарлаа",

    // Alert Box / Alerts
    alertSubtitle: "2+ Dashboard-д илэрсэн CIF-үүд",
    alertMinDash: "Хамгийн бага:",
    alertLoading: "12 Dashboard шалгаж байна...",
    alertCifSearch: "CIF хайх... (шууд Oracle-с хайна)",
    alertOracleSearching: "Oracle-с хайж байна...",
    alertTransactions: "гүйлгээ",
    alertLoadingDetail: "Дэлгэрэнгүй ачааллаж байна...",
    alertRows: "мөр",
    alertNoResult: "Alert илэрсэнгүй",
    searchSubtitle: "12 Dashboard дээр CIF хайлт",
    searchLoading: "12 Dashboard хайж байна...",

    // Alert Box / Dashboards
    // Alert Box / Red Flag
    redflagSubtitle: "Event Chain дүрмийн илэрцүүд",
    redflagLoading: "12 Dashboard-ийн Event Chain шалгаж байна...",
    redflagTotalRules: "Нийт дүрэм",
    redflagActive: "Идэвхжсэн",
    redflagTotalMatches: "Нийт давхцал",
    redflagNoResult: "Илэрц олдсонгүй",

    // Sanamsargui tuuwer (Random sampling)
    sampleTitle: "Санамсаргүй түүвэр",
    sampleSubtitle: "Excel файлаас санамсаргүй дээж сонгох",
    samplePreparing: "Excel бэлтгэж байна...",
    sampleWait: "Түр хүлээнэ үү",
    sampleDesign: "Түүврийн дизайн",
    sampleConfidence: "Итгэлийн түвшин",
    sampleErrorMargin: "Алдааны марж (%)",
    sampleStdDev: "Стандарт хазайлт (σ)",
    sampleFileName: "Хадгалах файлын нэр",
    sampleSaveDialog: "Хадгалах цонх ашиглах",
    sampleUploadFile: "Excel файл оруулах",
    sampleDropZone: "Файл чирж оруулах буюу дарж сонгох",
    sampleFilterByCol: "Баганаар шүүх",
    sampleFilterCol: "Шүүх багана",
    sampleFilterValues: "Утгын шүүлтүүр",
    sampleSelectCol: "— Багана сонгоно —",
    sampleSearchValues: "Утга хайх...",
    sampleAllValues: "Бүх утга",
    sampleCollapse: "Хураах",
    sampleForceAll: "Бүх утгыг заавал хамруулах",
    sampleNoFilter: "⚠️ Сонгосон баганад илэрц олдсонгүй.",
    sampleSizeLabel: "Тооцоологдсон түүврийн хэмжээ",
    samplePopN: "Эх олонлогийн тоо (N)",
    sampleGroupN: "Бүлгийн тоо (≥2)",
    sampleSeed: "Seed (давтагдах түүвэр)",
    sampleSeedPlaceholder: "ж: 2026-Q1-audit (заавал биш)",
    sampleSeedHint:
      "Seed оруулбал ижил өгөгдөл дээр яг ижил түүвэр дахин гарна — аудитын нотлох боломж.",

    // Reports tool
    reportsLoadError: "Тайлан ачаалахад алдаа гарлаа",
    reportsNoAccess: "Эрхтэй тайлан байхгүй байна",
    reportsDateInstant: "Шууд татах",
    reportsDateSingle: "Нэг огноо",
    reportsDateRange: "Хугацааны интервал",
    reportsToolNotFound: "Tool олдсонгүй",
    reportsToolLoadError: "Мэдээлэл татахад алдаа гарлаа",
    reportsDateRequired: "Огноо оруулна уу",
    reportsFilterRequired: "Заавал шүүлтүүр бөглөнө үү",
    reportsDownloadSuccess: "Амжилттай татлаа",
    reportsDownloadCanceled: "Таталтыг зогсооллоо",
    reportsPreviewCanceled: "Preview-г зогсооллоо",
    reportsDateRangeLabel: "Огнооны интервал",
    reportsDateStart: "Эхлэх",
    reportsDateEnd: "Дуусах",
    reportsDateSingleLabel: "Огноо",
    reportsDateNone: "Огноо шаардлагагүй",
    reportsFiltersLabel: "Шүүлтүүрүүд",
    reportsFilterRequiredMsg: "Заавал шаардлагатай",
    reportsDownloading: "Татаж байна...",
    reportsDownloadDone: "Дууслаа ✓",
    reportsStopBtn: "Зогсоох",
    reportsOutputExcel: "Excel татах",
    reportsOutputCsv: "CSV татах",
    reportsStatTotal: "Нийт мөр",
    reportsStatColumns: "Багана",
    reportsStatSize: "Хэмжээ",
    reportsStatRows: "мөр",
    reportsPreviewEmpty: "Preview хоосон байна",
    reportsPreviewEmptyHint: "Огноо сонгоод Preview дарна уу",
    reportsPreviewEmptyHintNoDate: "Preview товч дарна уу",
    reportsPreviewError: "Preview алдаа",
    reportsPreviewFirst: "эхний",
    reportsPreviewColumns: "багана",
    reportsPreviewTotal: "нийт",
    dbAccessMyGrants: "Идэвхтэй эрхүүд",
    dbAccessManage: "Хүсэлт шийдвэрлэх",
    dbAccessLoadError: "Хүснэгтүүд ачаалахад алдаа гарлаа",
    dbAccessTableSearch: "Хүснэгт хайх...",
    dbAccessTableUnit: "хүснэгт",
    dbAccessSelectTableHint: "← Хүснэгт сонгоно уу",
    dbAccessSelectSection: "Хүснэгт сонгох",
    dbAccessExpirySection: "Хугацаа & Шалтгаан",
    dbAccessExpiryDate: "Дуусах огноо",
    dbAccessExpiryTime: "Дуусах цаг",
    dbAccessReason: "Шалтгаан (заавал)",
    dbAccessReasonPlaceholder: "Яагаад энэ эрх хэрэгтэй байгаагаа бичнэ үү...",
    dbAccessSubmitBtn: "Хүсэлт илгээх",
    dbAccessValidationTitle: "Сонголт хийнэ үү",
    dbAccessValidationNoTable: "Хамгийн багадаа нэг хүснэгт сонгоно уу",
    dbAccessValidationDate: "Огноо оруулна уу",
    dbAccessValidationDateRequired: "Эрхийн дуусах огноог заавал оруулна уу",
    dbAccessValidationReason: "Шалтгаан оруулна уу",
    dbAccessValidationReasonRequired: "Эрх хүссэн шалтгааныг заавал бичнэ үү",
    dbAccessValidationBadDate: "Буруу огноо",
    dbAccessValidationFutureDate: "Дуусах хугацаа ирээдүйд байх ёстой",
    dbAccessRequestSent: "Хүсэлт илгээгдлээ",
    dbAccessRequestSentMsg: "хүснэгтэд эрх хүсэх хүсэлт амжилттай илгээгдлээ",
    dbAccessRequestError: "Хүсэлт илгээхэд алдаа гарлаа",

    // DB Access (manage/grant)
    dbManagePendingTab: "Хүлээгдэж буй",
    dbManageAllTab: "Бүх хүсэлт",
    dbManageGrantsTab: "Хэрэглэгчийн эрхийн жагсаалт",
    dbManageNoPending: "Одоогоор баталгаажаагүй хүсэлт алга.",
    dbManageNoRequests: "Хүсэлт байхгүй",
    dbManageSentAt: "Илгээсэн:",
    dbManageValidUntil: "Хүчинтэй:",
    dbManageResolvedAt: "Шийдвэрлэсэн:",
    dbManageTables: "Хүснэгтүүд",
    dbManageGrantType: "Эрхийн төрөл",
    dbManageReasonLabel: "Шалтгаан",
    dbManageDecisionNote: "Тайлбар (заавал)",
    dbManageDecisionPlaceholder: "Шийдвэрийн тайлбар...",
    dbManageApprove: "Батлах",
    dbManageReject: "Татгалзах",
    dbManageResolveBtn: "Шийдвэрлэх",
    dbManageConfirmDelete: "Энэ хүсэлтийг бүрмөсөн устгах уу?",
    dbManageApproved: "Зөвшөөрлөө",
    dbManageRejected: "Татгалзлаа",
    dbManageActionError: "Үйлдэл амжилтгүй",
    dbManageDeleteError: "Устгахад алдаа гарлаа",
    dbManageHistoryConfirm:
      "Бүх шийдвэрлэгдсэн хүсэлтийн түүхийг устгах уу? (Хүлээгдэж байгаа хүсэлтүүд хэвээр үлдэна)",
    dbManageHistoryDeleted: "Түүх устгагдлаа",
    dbManageRevoked: "Эрх цуцлагдлаа",
    dbManageRevokeError: "Цуцлахад алдаа гарлаа",
    dbManageCleanError: "CH цэвэрлэхэд алдаа гарлаа",
    dbManageCleaned: "CH хандалт цэвэрлэгдлээ",
    dbManageStatusPending: "Хүлээгдэж байна",
    dbManageStatusApproved: "Зөвшөөрөгдсөн",
    dbManageStatusRejected: "Татгалзсан",

    // My Grants page
    dbManageTitle: "Хүсэлт шийдвэрлэх",
    dbManageSubtitle: "Хандалтын хүсэлтүүдийг удирдах",
    dbManageSummary: "Нийт",
    dbManageGrantUnit: "эрх",
    dbManageUserUnit: "хэрэглэгч",
    dbManageRevokeBtn: "Цуцлах",
    myGrantsTitle: "Миний Идэвхтэй Эрхүүд",
    myGrantsSubtitle: "Одоогийн хандалтын зөвшөөрлүүд",
    myGrantsEmpty: "Идэвхтэй эрх байхгүй",
    myGrantsEmptyHint: "Эрх хүсэхийн тулд хүсэлт илгээнэ үү",
    myGrantsRequestBtn: "Эрх хүсэх",
    myGrantsGrantedBy: "Олгосон:",
    myGrantsExpiresLabel: "Хаагдах:",
    myGrantsExpired: "Хугацаа дууссан",
    myGrantsDaysLeft: "өдөр үлдсэн",
    myGrantsCloseBtn: "Хаах",
    myGrantsCloseTitle: "Эрхийг хугацаанаас өмнө хаах",
    myGrantsChCreds: "ClickHouse Нэвтрэх мэдээлэл",
    myGrantsChUser: "Хэрэглэгч:",
    myGrantsChPassword: "Нууц үг:",
    myGrantsCopyUser: "Хэрэглэгч нэр",
    myGrantsCopyPwd: "Нууц үг",

    // Risk Assessment tool
    riskMonitorCardTitle: "Эрсдэлийн хяналт",
    riskDoAssessCardTitle: "Эрсдэлийн үнэлгээ хийх",
    riskBranchSubtitle: "Салбарын үнэлгээ",
    riskDetailSubtitle: "Мөр бүрийн дэлгэрэнгүй",
    riskSavePlaceholder: "Жишээ: 2025 Q4 Улирал",
    riskSaveError: "Хадгалахад алдаа",
    riskSaveSuccess:
      "Тайлан амжилттай хадгалагдлаа! Тайлангууд хуудаснаас үзэх боломжтой.",
  },
  en: {
    // Navigation & common
    logout: "Sign out",
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    // Settings page
    changeImage: "Choose photo",
    removeImage: "Remove photo",
    imageSuccess: "Profile photo updated successfully",
    imageRemoved: "Profile photo removed",
    imageError: "Failed to save photo",
    imageTooBig: "Photo is too large. Please choose a smaller image.",
    imageHint1: "Maximum file size 5MB",
    imageHint3: "JPG, PNG, GIF formats supported",

    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    currentPasswordPlaceholder: "Enter your current password",
    newPasswordPlaceholder: "Enter your new password",
    confirmPasswordPlaceholder: "Re-enter your new password",
    passwordReq1: "At least 8 characters",
    passwordReq2: "Contains uppercase letter (A-Z)",
    passwordReq3: "Contains lowercase letter (a-z)",
    passwordReq4: "Contains a number (0-9)",
    passwordReq5: "Contains special character (@$!%*?&#)",
    passwordMismatch: "Passwords do not match",
    passwordInvalid: "Password does not meet requirements",
    passwordFillAll: "Please fill in all fields",
    passwordChangeBtn: "Change password",

    navHome: "Home",
    navDepartments: "Departments",
    navEmployees: "Employees",
    navNews: "Knowledge",
    navTools: "Tools",
    navAdmin: "Admin",
    navAdminPanel: "Admin panel",
    navUsers: "Users",
    navTheme: "Theme",
    navProfileSettings: "Profile settings",

    // Common UI
    needLogin: "Login required",
    needLoginToolsDesc: "Please sign in to use tools.",
    needLoginDeptDesc: "Please sign in to view this page.",

    // Tools page
    toolsPageTitle: "Tools",
    toolsPageSubtitle: "Internal Audit Division",
    toolsOpen: "Open",
    toolsNoneFound: "No tools found",
    toolsNoneDesc:
      "You don't have access to any tools. Contact your admin to request access.",
    toolSampleTitle: "Random sampling",
    toolSampleDesc: "Tool for generating random audit samples",
    toolPivotTitle: "Pivot",
    toolPivotDesc: "Create pivot tables from Excel files",
    toolReportTitle: "Quarterly report",
    toolReportDesc: "Prepare quarterly work reports",
    toolDbRequestTitle: "Request access",
    toolDbRequestDesc:
      "Request access to ClickHouse tables and manage your requests",
    toolDbGrantTitle: "Grant access",
    toolDbGrantDesc: "Review and manage ClickHouse access requests",
    toolDataDocTitle: "Data dictionary",
    toolDataDocDesc:
      "ClickHouse database structure, column descriptions, and code library",
    toolAlertBoxTitle: "Alert Box",
    toolAlertBoxDesc:
      "Transaction risk analysis, CIF search, and red-flag alerts",
    toolRiskAssessmentTitle: "Risk Assessment",
    toolRiskAssessmentDesc:
      "Monthly risk assessment — department scores, manual adjustments, and audit log",
    toolReportsTitle: "Reports",
    toolReportsDesc:
      "Download SQL and Python reports from a single unified tool",

    // Departments page
    managerBadge: "Manager",
    youBadge: "You",
    noEmployees: "No employees registered",
    deptsLoadError: "Failed to load departments.",
    noNews: "No articles available",
    minRead: "min",
    newsDefaultAuthor: "Internal Audit",
    internalAuditDept: "Internal Audit Division",
    newsCreateError: "Failed to add article",
    newsDeleteConfirm: "Delete this article?",
    newsDeleteError: "Failed to delete article",
    newsCommentPlaceholder: "Write a comment...",
    newsCommentEmpty: "No comments yet",
    newsCommentError: "Failed to add comment",
    // Tailan (Quarterly Report) tool
    tailan_title: "Quarterly Report",
    tailan_myReport: "My Report",
    tailan_deptReport: "Department Report",
    tailan_membersView: "View Members' Reports",
    tailan_membersViewDesc: "View submitted reports from department members",
    tailan_myReportTitle: "My Report",
    tailan_downloadWord: "Download Word",
    tailan_submitReport: "Submit",
    tailan_cyrillicName: "Name (Cyrillic)",
    tailan_cyrillicNamePlaceholder:
      "Enter your name as it will appear in the report",
    tailan_yearLabel: "Year",
    tailan_quarterLabel: "Quarter",
    tailan_s1Title:
      "I. Support for audit activities through data analysis results",
    tailan_s12Title: "I.2 Quality and results of newly developed Dashboard",
    tailan_s2Title: "II. Data processing tasks required for audit activities",
    tailan_s3Title: "III. Recurring tasks",
    tailan_s31Title: "III.1 Timely execution of data processing automation",
    tailan_s32Title: "III.2 Maintaining normal dashboard operations",
    tailan_s4Title: "IV. Training attended",
    tailan_s41Title: "IV.1 Application of knowledge gained from training",
    tailan_s5Title: "V. Assigned task completion",
    tailan_s6Title: "VI. Team activities",
    tailan_s7Title: "VII. New proposals and initiatives",
    tailan_dynTitle: "Additional sections (VIII, IX, …)",
    tailan_showInReport: "Show in report",
    tailan_hideFromReport: "Hide from report",
    tailan_addTask: "Add task",
    tailan_addEntry: "Add",
    tailan_addTraining: "Add training",
    tailan_addSection: "Add extra section",
    tailan_taskNameLabel: "Task name",
    tailan_taskDescLabel: "Completion /description/",
    tailan_detailedDescPlaceholder: "Write a detailed description...",
    tailan_taskNamePlaceholder: "Task name...",
    tailan_plannedTaskLabel: "Planned task",
    tailan_taskCompletionPct: "Task completion (%)",
    tailan_periodLabel: "Period completed",
    tailan_startDateLabel: "Start date",
    tailan_endDateLabel: "End date",
    tailan_taskSummaryLabel: "Completion /brief/",
    tailan_briefSummaryPlaceholder: "Brief description...",
    tailan_plannedTaskPlaceholder: "Planned task name...",
    tailan_autoTaskPlaceholder: "Recurring automation...",
    tailan_valueUsagePlaceholder: "Value/usage...",
    tailan_userRatingPlaceholder: "User rating (0-100)",
    tailan_dashboardNamePlaceholder: "Dashboard name...",
    tailan_clientRatingPlaceholder: "Client unit rating (0-100)",
    tailan_trainingNamePlaceholder: "Training name...",
    tailan_organizerLabel: "Organizer",
    tailan_trainingTypeLabel: "Training type",
    tailan_selectOption: "-- Select --",
    tailan_externalTraining: "External",
    tailan_internalTraining: "Internal",
    tailan_trainingFormatLabel: "Training format",
    tailan_onlineFormat: "Online",
    tailan_inPersonFormat: "In-person",
    tailan_hoursLabel: "Hours",
    tailan_meetsGoalLabel: "Meets audit goal",
    tailan_meetsGoalYes: "Yes",
    tailan_meetsGoalNo: "No",
    tailan_sharedKnowledgeLabel: "Shared knowledge",
    tailan_sharedKnowledgeYes: "Shared",
    tailan_sharedKnowledgeNo: "Not shared",
    tailan_knowledgeUsagePlaceholder:
      "How knowledge from training is being applied...",
    tailan_teamActivityPlaceholder: "Team activity...",
    tailan_initiativeLabel: "Initiative",
    tailan_proposalPlaceholder: "Write new proposals and ideas...",
    tailan_sectionTitlePlaceholder: "Section title...",
    tailan_sectionContentPlaceholder: "Section content...",
    tailan_livePreview: "Realtime preview — Word document",
    tailan_dateLabel: "Date",
    tailan_viewReportTitle: "View report",
    tailan_reportLoading: "Loading report...",
    tailan_noReportSubmitted: "has not submitted a report this quarter.",
    tailan_noReportsThisQuarter: "No reports registered for this quarter",
    tailan_submitted: "Submitted",
    tailan_draft: "Draft",
    tailan_submittedAtLabel: "Submitted:",
    tailan_updatedAtLabel: "Updated:",
    tailan_viewReportHint: "View report",
    tailan_deptReportPageTitle: "Department quarterly report",
    tailan_savingLabel: "Saving...",
    tailan_collapseSidebar: "Collapse",
    tailan_expandSidebar: "Expand",
    tailan_evalTitle: "Summary / Evaluation",
    tailan_totalScoreLabel: "Total score:",
    tailan_allSectionsOverview: "All sections overview",
    tailan_s1Label: "Board & Audit Committee Status",
    tailan_s2Label: "Customer Status",
    tailan_s3Label: "Internal Operations Status",
    tailan_s4Label: "Learning & Development Status",
    tailan_scorePointsSuffix: "pts",
    tailan_detailedEvalTable: "Detailed evaluation table",
    tailan_groupCol: "Group",
    tailan_keyIndicatorCol: "Key indicator",
    tailan_weightCol: "Weight",
    tailan_scoreCol: "Score",
    tailan_scoreDescCol: "Score description",
    tailan_subtotalRow: "Total",
    tailan_grandTotalRow: "TOTAL",
    tailan_signatureSection: "Signature",
    tailan_namePlaceholder: "Name...",
    tailan_titleJobPlaceholder: "/Title/",
    tailan_preparedBy: "PREPARED BY:",
    tailan_evaluatedBy: "EVALUATED & VALIDATED BY:",
    tailan_previewSection: "Preview",
    tailan_lastSavedLabel: "Last:",
    tailan_generalDescLabel: "General description",
    tailan_generalDescPlaceholder:
      "Write a detailed description of work and activities carried out within this perspective...",
    tailan_achievementsLabel: "Achievements and strengths",
    tailan_achievementsPlaceholder:
      "Note achievements, good results, and strengths during the reporting period...",
    tailan_challengesLabel: "Challenges",
    tailan_challengesPlaceholder:
      "Note challenges and issues requiring resolution during the reporting period...",
    tailan_widthLabel: "Width:",
    tailan_heightLabel: "Height:",
    tailan_productNamePlaceholder: "Product name...",
    tailan_sectionNamePlaceholder: "Section name...",
    tailan_dataProductCol: "DATA PRODUCT",
    tailan_productTypeCol: "PRODUCT TYPE",
    tailan_savedDaysCol: "PERSON-DAYS SAVED",
    tailan_completionBriefCol: "Completion /brief/",
    tailan_dataProcessingCol: "Data processing",
    tailan_imageWidthSettings: "Image width settings",
    tailan_periodPlaceholder: "Period...",
    tailan_completionBriefPlaceholder: "Completion /brief/...",
    tailan_bulletTextPlaceholder: "Bullet text...",
    tailan_employeeNamePlaceholder: "Employee name...",
    tailan_kpiIndicatorPlaceholder: "Indicator...",
    tailan_kpiEvaluationPlaceholder: "Description...",
    tailan_scoreExcellent: "Excellent",
    tailan_scoreGood: "Good",
    tailan_scoreSatisfactory: "Satisfactory",
    tailan_scoreAverage: "Average",
    tailan_scoreInsufficient: "Insufficient",
    tailan_dataProcessingNamePlaceholder: "Data processing name...",
    tailan_imagesCount: "images",
    tailan_taskResultLabel: "Task Result",
    tailan_taskDetailedPlaceholder: "Write a detailed description...",
    tailan_deleteAction: "Delete",
    tailan_addImage: "+ Add Image",
    tailan_s14NewProducts:
      "New data products introduced during the reporting period",
    tailan_s14UsedProducts: "Data products used during the reporting period",
    tailan_noData: "No data",
    tailan_fetchFromPersonal: "Fetch from personal report",
    tailan_descriptionText: "Description text",
    tailan_s14ResourceSavedPlaceholder:
      "Description of resources and time saved...",
    tailan_plannedTaskCol: "Planned Task",
    tailan_taskCompletionCol: "Task Completion",
    tailan_taskPeriodCol: "Period",
    tailan_noTasksHint: "No tasks — click fetch or add button",
    tailan_avgLabel: "Average",
    tailan_unnamed: "(unnamed)",
    tailan_usageSignificanceCol: "Usage & Significance",
    tailan_clientScoreCol: "Client Score",
    tailan_clickFetchHint: "Click fetch button",
    tailan_usagePlaceholder: "Usage & significance...",
    tailan_scorePlaceholder: "Score...",
    tailan_addRow: "+ Add Row",
    tailan_taskNameHeader: "Task Name",
    tailan_completionPctHeader: "Completion %",
    tailan_completionBriefHeader: "Completion /brief/",
    tailan_periodHeader: "Period",
    tailan_regularDataProcessingCol: "Regular Data Processing",
    tailan_dashUsageCol: "Dashboard Usage & Significance",
    tailan_dashNamePlaceholder: "Dashboard name...",
    tailan_noItemsHint: "No items — click add button",
    tailan_titlePlaceholder: "Title...",
    tailan_deleteItemAction: "Delete item",
    tailan_addBullet: "+ Add Bullet",
    tailan_addItem: "+ Add Item",
    tailan_s43employeeHeader: "Employee",
    tailan_s43trainingHeader: "Training Name",
    tailan_s43organizerHeader: "Organizer",
    tailan_s43typeHeader: "Type",
    tailan_s43dateHeader: "Date",
    tailan_s43formatHeader: "Format",
    tailan_s43hoursHeader: "Hours",
    tailan_s43meetsGoalHeader: "Meets Audit Goal",
    tailan_s43sharedHeader: "Shared Knowledge",
    tailan_s43employeePlaceholder: "Employee...",
    tailan_s43trainingPlaceholder: "Training...",
    tailan_s43organizerPlaceholder: "Organizer...",
    tailan_s43typePlaceholder: "Type...",
    tailan_s43datePlaceholder: "Date...",
    tailan_s43formatPlaceholder: "Format...",
    tailan_s43hoursPlaceholder: "Hours...",
    tailan_s43meetsGoalPlaceholder: "Yes/No...",
    tailan_s43sharedPlaceholder: "Knowledge...",
    tailan_keyIndicatorHeader: "Key Indicator",
    tailan_weightPctHeader: "Weight %",
    tailan_scoreHeader: "Score",
    tailan_evaluatedDescHeader: "Evaluation Description",
    tailan_s4ContentLabel: "Training & Development Content",
    tailan_s4ContentPlaceholder: "Write training and development content...",

    // Common / shared UI
    accessDenied: "Access restricted",
    accessDeniedMsg:
      "You don't have permission to use this tool. Contact your admin.",
    viewGrouped: "Group",
    viewTable: "Table",
    // Pivot tool
    pivotTitle: "Pivot & sample calculation",
    pivotSubtitle:
      "Group by code, pivot by year, calculate sample and export to Excel",
    pivotFileLabel: "Upload Excel or CSV file",
    pivotDropZone: "Drag and drop or click to select a file",
    pivotFileError: "Please upload an Excel (.xlsx, .xls) or CSV file",
    pivotNoData: "Not enough data in file",
    pivotYearFilter: "Year filter",
    pivotAllYears: "All years",
    pivotDateCol: "Date column",
    pivotGroupCol: "Group column",
    pivotPrefixLen: "Prefix length",
    pivotConfError: "Confidence / Error",
    pivotCreateBtn: "Create pivot",
    pivotResultTitle: "Pivot by code group",
    pivotExportBtn: "Download Excel",

    // Data dictionary tool
    dataDocCodeLib: "Code library",
    dataDocCodeSaved: "snippets saved",
    dataDocDbLabel: "Database",
    dataDocSelectDb: "Select DB",
    dataDocSearchTable: "Search tables…",
    dataDocNoTables: "No tables found",
    dataDocSelectTableHint: "← Select a table",
    dataDocColName: "Column name",
    dataDocColType: "Type",
    dataDocColDesc: "Description",
    dataDocFiltered: "With description",
    dataDocUnfiltered: "Without description",
    dataDocSearchCol: "Search columns…",
    dataDocDescPlaceholder: "Enter description…",
    dataDocSaving: "Saving…",
    dataDocSaveError: "Save failed",

    // Alert Box / Alerts
    alertSubtitle: "CIFs found in 2+ dashboards",
    alertMinDash: "Minimum:",
    alertLoading: "Checking 12 dashboards...",
    alertCifSearch: "Search CIF... (direct Oracle search)",
    alertOracleSearching: "Searching Oracle...",
    alertTransactions: "transactions",
    alertLoadingDetail: "Loading details...",
    alertRows: "rows",
    alertNoResult: "No alerts found",
    searchSubtitle: "CIF search across 12 dashboards",
    searchLoading: "Searching 12 dashboards...",

    // Alert Box / Dashboards
    // Alert Box / Red Flag
    redflagSubtitle: "Event chain rule matches",
    redflagLoading: "Checking event chains in 12 dashboards...",
    redflagTotalRules: "Total rules",
    redflagActive: "Active",
    redflagTotalMatches: "Total matches",
    redflagNoResult: "No matches found",

    // Sanamsargui tuuwer (Random sampling)
    sampleTitle: "Random Sampling",
    sampleSubtitle: "Select random samples from an Excel file",
    samplePreparing: "Preparing Excel...",
    sampleWait: "Please wait",
    sampleDesign: "Sample design",
    sampleConfidence: "Confidence level",
    sampleErrorMargin: "Error margin (%)",
    sampleStdDev: "Standard deviation (σ)",
    sampleFileName: "Save file name",
    sampleSaveDialog: "Use save dialog",
    sampleUploadFile: "Upload Excel file",
    sampleDropZone: "Drag and drop or click to select",
    sampleFilterByCol: "Filter by column",
    sampleFilterCol: "Filter column",
    sampleFilterValues: "Value filter",
    sampleSelectCol: "— Select column —",
    sampleSearchValues: "Search values...",
    sampleAllValues: "All values",
    sampleCollapse: "Collapse",
    sampleForceAll: "Force include all values",
    sampleNoFilter: "⚠️ No matches found in selected column.",
    sampleSizeLabel: "Calculated sample size",
    samplePopN: "Population size (N)",
    sampleGroupN: "Number of groups (≥2)",
    sampleSeed: "Seed (reproducible sampling)",
    sampleSeedPlaceholder: "e.g. 2026-Q1-audit (optional)",
    sampleSeedHint:
      "With a seed, the exact same sample is reproduced on the same data — audit evidence.",

    // Reports tool
    reportsLoadError: "Failed to load reports",
    reportsNoAccess: "No accessible reports",
    reportsDateInstant: "Instant download",
    reportsDateSingle: "Single date",
    reportsDateRange: "Date range",
    reportsToolNotFound: "Tool not found",
    reportsToolLoadError: "Failed to load tool info",
    reportsDateRequired: "Please enter a date",
    reportsFilterRequired: "Please fill required filters",
    reportsDownloadSuccess: "Download successful",
    reportsDownloadCanceled: "Download canceled",
    reportsPreviewCanceled: "Preview canceled",
    reportsDateRangeLabel: "Date range",
    reportsDateStart: "Start",
    reportsDateEnd: "End",
    reportsDateSingleLabel: "Date",
    reportsDateNone: "No date required",
    reportsFiltersLabel: "Filters",
    reportsFilterRequiredMsg: "Required",
    reportsDownloading: "Downloading...",
    reportsDownloadDone: "Done ✓",
    reportsStopBtn: "Stop",
    reportsOutputExcel: "Download Excel",
    reportsOutputCsv: "Download CSV",
    reportsStatTotal: "Total rows",
    reportsStatColumns: "Columns",
    reportsStatSize: "Size",
    reportsStatRows: "rows",
    reportsPreviewEmpty: "Preview is empty",
    reportsPreviewEmptyHint: "Select a date and click Preview",
    reportsPreviewEmptyHintNoDate: "Click the Preview button",
    reportsPreviewError: "Preview error",
    reportsPreviewFirst: "first",
    reportsPreviewColumns: "columns",
    reportsPreviewTotal: "total",
    dbAccessMyGrants: "Active grants",
    dbAccessManage: "Manage requests",
    dbAccessLoadError: "Failed to load tables",
    dbAccessTableSearch: "Search tables...",
    dbAccessTableUnit: "tables",
    dbAccessSelectTableHint: "← Select a table",
    dbAccessSelectSection: "Select tables",
    dbAccessExpirySection: "Expiry & Reason",
    dbAccessExpiryDate: "Expiry date",
    dbAccessExpiryTime: "Expiry time",
    dbAccessReason: "Reason (required)",
    dbAccessReasonPlaceholder: "Describe why you need this access...",
    dbAccessSubmitBtn: "Submit request",
    dbAccessValidationTitle: "Make a selection",
    dbAccessValidationNoTable: "Please select at least one table",
    dbAccessValidationDate: "Enter date",
    dbAccessValidationDateRequired: "Expiry date is required",
    dbAccessValidationReason: "Enter reason",
    dbAccessValidationReasonRequired: "Please provide a reason",
    dbAccessValidationBadDate: "Invalid date",
    dbAccessValidationFutureDate: "Expiry date must be in the future",
    dbAccessRequestSent: "Request sent",
    dbAccessRequestSentMsg: "table access request(s) sent successfully",
    dbAccessRequestError: "Failed to send request",

    // DB Access (manage/grant)
    dbManagePendingTab: "Pending",
    dbManageAllTab: "All requests",
    dbManageGrantsTab: "User grants",
    dbManageNoPending: "No pending requests.",
    dbManageNoRequests: "No requests",
    dbManageSentAt: "Sent:",
    dbManageValidUntil: "Valid until:",
    dbManageResolvedAt: "Resolved:",
    dbManageTables: "Tables",
    dbManageGrantType: "Grant type",
    dbManageReasonLabel: "Reason",
    dbManageDecisionNote: "Note (required)",
    dbManageDecisionPlaceholder: "Decision note...",
    dbManageApprove: "Approve",
    dbManageReject: "Reject",
    dbManageResolveBtn: "Resolve",
    dbManageConfirmDelete: "Permanently delete this request?",
    dbManageApproved: "Approved",
    dbManageRejected: "Rejected",
    dbManageActionError: "Action failed",
    dbManageDeleteError: "Delete failed",
    dbManageHistoryConfirm:
      "Delete all resolved request history? (Pending requests will remain.)",
    dbManageHistoryDeleted: "History deleted",
    dbManageRevoked: "Access revoked",
    dbManageRevokeError: "Failed to revoke",
    dbManageCleanError: "Failed to clean CH access",
    dbManageCleaned: "CH access cleaned",
    dbManageStatusPending: "Pending",
    dbManageStatusApproved: "Approved",
    dbManageStatusRejected: "Rejected",

    // My Grants page
    dbManageTitle: "Manage Requests",
    dbManageSubtitle: "Review and manage access requests",
    dbManageSummary: "Total",
    dbManageGrantUnit: "grants",
    dbManageUserUnit: "users",
    dbManageRevokeBtn: "Revoke",
    myGrantsTitle: "My Active Grants",
    myGrantsSubtitle: "Current access permissions",
    myGrantsEmpty: "No active grants",
    myGrantsEmptyHint: "Submit a request to get access",
    myGrantsRequestBtn: "Request access",
    myGrantsGrantedBy: "Granted by:",
    myGrantsExpiresLabel: "Expires:",
    myGrantsExpired: "Expired",
    myGrantsDaysLeft: "days left",
    myGrantsCloseBtn: "Close",
    myGrantsCloseTitle: "Close grant early",
    myGrantsChCreds: "ClickHouse Credentials",
    myGrantsChUser: "Username:",
    myGrantsChPassword: "Password:",
    myGrantsCopyUser: "Username",
    myGrantsCopyPwd: "Password",

    // Risk Assessment tool
    riskMonitorCardTitle: "Risk Monitoring",
    riskDoAssessCardTitle: "Do Risk Assessment",
    riskBranchSubtitle: "Branch assessment",
    riskDetailSubtitle: "Detail by row",
    riskSavePlaceholder: "Example: 2025 Q4 Quarter",
    riskSaveError: "Save error",
    riskSaveSuccess:
      "Report saved successfully! You can view it from the Reports page.",
  },
} as const;

export type TranslationKey = keyof typeof translations.mn;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "mn",
  setLanguage: () => {},
  t: (key) => translations.mn[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("mn");

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Language | null;
    if (saved === "mn" || saved === "en") setLanguageState(saved);
  }, []);

  const value = useMemo<LanguageContextType>(
    () => ({
      language,
      setLanguage: (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("lang", lang);
      },
      t: (key: TranslationKey) => translations[language][key],
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
